(defpackage #:docling-exchange-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-exchange-tests)
(defvar *checks* 0)
(defvar *atol* 2e-5)
(defvar *rate* 0.03)
(defun check (value label) (incf *checks*) (unless value (error "Adapter exchange: ~A" label)))
(defun close-arrays (a b &optional (atol *atol*) (rtol 3e-4))
  (check (equal (array-dimensions a) (array-dimensions b)) "shape")
  (dotimes (i (array-total-size a))
    (check (<= (abs (- (row-major-aref a i) (row-major-aref b i)))
               (+ atol (* rtol (abs (row-major-aref b i))))) "reference value")))
(defun ints (tensor)
  (let* ((a (tb:tensor-array tensor)) (b (make-array (array-dimensions a))))
    (dotimes (i (array-total-size a) b) (setf (row-major-aref b i) (round (row-major-aref a i))))))
(defun rejected (thunk)
  (check (handler-case (progn (funcall thunk) nil)
           (tb:backend-error () t) (docling:layout-error () t)) "reject unsafe/unsupported artifact"))
(defun loss (model ids features labels mask)
  (multiple-value-bind (value gradients)
      (docling:document-loss-and-gradients model ids features :labels labels :attention-mask mask)
    (mapc (lambda (p) (tb:dispose (cdr p))) gradients) value))
(defun snapshot (model)
  (mapcar (lambda (p) (cons (car p) (tb:tensor-array (cdr p)))) (tb:named-parameters model)))
(defun frozen-p (model original)
  (dolist (p original)
    (close-arrays (cdr p) (tb:tensor-array (cdr (assoc (car p) (tb:named-parameters model) :test #'equal))) 0 0)))
(defun observe (model backend root name ids features labels mask)
  (tb:with-resource (logits (docling:forward-document model ids :image-features features :attention-mask mask))
    (let* ((value (loss model ids features labels mask))
           (n (position-if (lambda (x) (/= -100 x)) (loop for i below (array-dimension labels 1) collect (aref labels 0 i))))
           (prompt (make-array (list 1 n))))
      (dotimes (i n) (setf (aref prompt 0 i) (aref ids 0 i)))
      (tbk:with-backend (backend)
        (let* ((one (tbk:take-indices features (tb:tensor-from-array backend #(0) :dtype :int32)))
               (tokens (docling:generate-document model prompt nil :image-features one :max-new-tokens 4 :eos-token-id nil)))
          (tbk:save-checkpoint (merge-pathnames name root) (make-hash-table :test 'equal)
            (list (cons "logits" logits) (cons "features" features)
                  (cons "tokens" (tb:tensor-from-array backend tokens))
                  (cons "loss" (tb:tensor-from-array backend (vector value)))) nil))))
    (tb:tensor-array logits)))
(defun merge-check (model backend root name ids features mask before)
  (declare (ignore backend))
  (docling:merge-document-lora model)
  (rejected (lambda () (docling:document-lora-parameters model)))
  (tb:with-resource (logits (docling:forward-document model ids :image-features features :attention-mask mask))
    (close-arrays before (tb:tensor-array logits)))
  (tb:save-pretrained model (merge-pathnames name root))
  (rejected (lambda () (docling:make-document-lora model :rank 2 :alpha 4))))
(defun run-tests ()
  (let* ((root (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_EXCHANGE")))
         (base (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_MODEL")))
         (fixture (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_TRAINING_FIXTURE")))
         (phase (uiop:getenv "DOCLING_EXCHANGE_PHASE"))
         (*atol* (if (uiop:getenv "DOCLING_EXCHANGE_REAL") 1e-3 2e-5))
         (*rate* (if (uiop:getenv "DOCLING_EXCHANGE_REAL") 0.001 0.03))
         (device (ecase (intern (string-upcase (or (uiop:getenv "TB_DEVICE") "cpu")) :keyword) (:cpu :cpu) (:gpu :gpu))))
    (tb:with-resource (backend (tb:make-backend :device device))
      (let ((baseline (getf (tb:backend-memory backend) :handles)))
        (tb:with-resource (model (docling:load-document-model base :backend backend))
          (let ((data (tbk:load-weight-file (merge-pathnames "inputs.safetensors" fixture) backend)))
            (unwind-protect
                 (let* ((ids (ints (gethash "ids" data))) (labels (ints (gethash "labels" data)))
                        (mask (ints (gethash "mask" data))) (original (snapshot model)))
                   (tb:with-resource (features (docling:document-image-features model (gethash "pixels" data)))
                     (cond
                       ((equal phase "export")
                        (docling:make-document-lora model :rank 2 :alpha 4 :seed 17)
                        (tb:with-resource (optimizer (tb:make-sgd :learning-rate *rate*))
                          (dotimes (i 3) (docling:document-train-step model optimizer ids features :labels labels :attention-mask mask)))
                        (frozen-p model original)
                        (docling:save-document-adapter model (merge-pathnames "native-adapter/" root))
                        (rejected (lambda () (docling:save-document-adapter model (merge-pathnames "native-adapter/" root))))
                        (tb:with-resource (loaded (docling:load-document-model base :backend backend))
                          (docling:load-document-adapter loaded (merge-pathnames "native-adapter/" root))
                          (loop for a in (docling:document-lora-parameters model)
                                for b in (docling:document-lora-parameters loaded) do
                                  (check (equal (car a) (car b)) "adapter names")
                                  (close-arrays (tb:tensor-array (cdr a)) (tb:tensor-array (cdr b)) 0 0)))
                        (let ((before (observe model backend root "native-observations/" ids features labels mask)))
                          (merge-check model backend root "native-merged/" ids features mask before)))
                       ((equal phase "reload")
                        (let ((handles (getf (tb:backend-memory backend) :handles)))
                          (dolist (dir (uiop:subdirectories (merge-pathnames "invalid/" root)))
                            (rejected (lambda () (docling:load-document-adapter model dir)))
                            (check (= handles (getf (tb:backend-memory backend) :handles)) "failed load cleanup")))
                        (docling:load-document-adapter model (merge-pathnames "python-adapter/" root))
                        (let ((transport (tbk:load-weight-file (merge-pathnames "python-adapter/adapter_model.safetensors" root) backend)))
                          (unwind-protect
                               (dolist (p (docling:document-lora-parameters model))
                                 (close-arrays (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) transport)) 0 0))
                            (tbk:dispose-weights transport)))
                        (rejected (lambda () (docling:load-document-adapter model (merge-pathnames "python-adapter/" root))))
                        (let ((expected (tbk:load-weight-file (merge-pathnames "python-observations.safetensors" root) backend)))
                          (unwind-protect
                               (progn
                                 (tb:with-resource (logits (docling:forward-document model ids :image-features features :attention-mask mask))
                                   (close-arrays (tb:tensor-array logits) (tb:tensor-array (gethash "logits" expected))))
                                 (check (< (abs (- (loss model ids features labels mask)
                                                  (aref (tb:tensor-array (gethash "loss" expected)) 0))) *atol*) "Python continued loss"))
                            (tbk:dispose-weights expected)))
                        (frozen-p model original)
                        (tb:with-resource (optimizer (tb:make-sgd :learning-rate *rate*))
                          (docling:document-train-step model optimizer ids features :labels labels :attention-mask mask))
                        (frozen-p model original)
                        (docling:save-document-adapter model (merge-pathnames "returned-adapter/" root))
                        (let ((before (observe model backend root "returned-observations/" ids features labels mask)))
                          (merge-check model backend root "returned-merged/" ids features mask before)))
                       (t (error "Unknown exchange phase")))))
              (tbk:dispose-weights data))))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "full cleanup")))
    (format t "~&PASS: ~D document adapter ~A checks on ~A.~%" *checks* phase device)))
