(defpackage #:cl-docling-application-tests (:use #:cl) (:export #:run-tests))
(in-package #:cl-docling-application-tests)
(defvar *checks* 0)
(defvar *reader-executed* nil)
(defun check (value label) (incf *checks*) (unless value (error "Check failed: ~A" label)))
(defun rejects (thunk label)
  (check (handler-case (progn (funcall thunk) nil) (error () t)) label))
(defun fresh ()
  (merge-pathnames (format nil "application-test-~D-~D/" (get-universal-time) (random 1000000000))
                  (asdf:system-relative-pathname "cl-docling" ".build/")))
(defun run-job (input output generator &rest options)
  (apply #'uiop:symbol-call :docling :run-pdf-job input output generator options))
(defun run-tests ()
  (let* ((*checks* 0)
         (input (asdf:system-relative-pathname "cl-docling" "tests/fixtures/pdf/native-pages.pdf"))
         (output (fresh)) (calls nil)
         (identity '("test-model" "unchanged-runtime"))
         (generator (lambda (image number)
                      (check (probe-file image) "generator receives real raster")
                      (push number calls)
                      (values (format nil "<doctag><text>Page ~D 日本語</text></doctag>" number)
                              #(4 9 49279) :eos))))
    (multiple-value-bind (bundle status report)
        (run-job input output generator :identity identity :pages '(1 2) :dpi 72)
      (check (eq status :complete) "two clean pages complete")
      (check (probe-file report) "attempt report saved")
      (check (equal (reverse calls) '(1 2)) "one call per selected page")
      (check (search "Page 2" (uiop:read-file-string (merge-pathnames "document.md" bundle))) "combined Markdown")
      (check (search "日本語" (uiop:read-file-string (merge-pathnames "page-2.doctags" bundle))) "raw Unicode preserved"))
    (setf calls nil)
    (run-job input output generator :identity identity :pages '(1 2) :dpi 72 :resume t)
    (check (null calls) "resume skips every committed page")
    (rejects (lambda () (run-job input output generator :identity identity :pages '(1 2) :dpi 72)) "existing job needs explicit resume")
    (dolist (options (list (list :identity '("changed")) (list :identity identity :dpi 144)
                          (list :identity identity :max-new-tokens 256)
                          (list :identity identity :pages '(2))
                          (list :identity identity :task "Different task")))
      (rejects (lambda () (apply #'run-job input output generator
                                (append options (list :resume t :identity identity :pages '(1 2) :dpi 72))))
               "resume rejects changed identity/options"))
    (check (null calls) "rejected resumes do not infer")
    (let* ((failed-output (fresh)) (fail t)
           (flaky (lambda (image number)
                    (when (and fail (= number 1)) (error "Injected page failure"))
                    (funcall generator image number))))
      (setf calls nil)
      (multiple-value-bind (bundle status report)
          (run-job input failed-output flaky :identity identity :pages '(1 2) :dpi 72)
        (check (null bundle) "failed job has no combined success bundle")
        (check (eq status :failed) "page exception is failed, not partial success")
        (check (search "Injected page failure" (uiop:read-file-string report)) "page failure retained")
        (check (equal calls '(2)) "later page still processed"))
      (setf fail nil calls nil)
      (multiple-value-bind (bundle status)
          (run-job input failed-output flaky :identity identity :pages '(1 2) :dpi 72 :resume t)
        (check (eq status :complete) "retry completes missing page")
        (check bundle "retry exports combined document")
        (check (equal calls '(1)) "retry does not repeat successful page"))
      (check (not (probe-file (merge-pathnames ".lock/" failed-output))) "lock released"))
    (dolist (reason '(:eos :length))
      (let ((path (fresh)))
        (multiple-value-bind (bundle status)
            (run-job input path (lambda (image number) (declare (ignore image number))
                                  (values "<doctag><chart>evidence</chart></doctag>" #(7) reason))
                     :identity identity :dpi 72)
          (check (eq status :blocked) "unsupported/truncated output blocks export")
          (check (probe-file (merge-pathnames "page-1.doctags" bundle)) "blocked raw persisted")
          (check (not (probe-file (merge-pathnames "document.md" bundle))) "no misleading Markdown"))))
    (dolist (options '((:pages nil) (:pages (2 1)) (:pages (1 1)) (:dpi 301)
                       (:max-new-tokens 0) (:max-new-tokens 4097) (:task "")))
      (let ((path (fresh)))
        (rejects (lambda () (apply #'run-job input path generator :identity identity options)) "invalid options fail")
        (check (not (probe-file path)) "invalid options have no output side effects")))
    (let ((missing (fresh)))
      (rejects (lambda () (run-job input missing generator :identity identity :resume t)) "resume cannot create job"))
    (let ((changed (make-pathname :type "pdf" :defaults (merge-pathnames "changed-input" (fresh)))))
      (ensure-directories-exist changed)
      (uiop:copy-file input changed)
      (with-open-file (s changed :direction :output :if-exists :append) (write-line "% changed" s))
      (rejects (lambda () (run-job changed output generator :identity identity :pages '(1 2) :dpi 72 :resume t))
               "changed input bytes reject resume"))
    (let ((link (fresh)))
      (sb-posix:symlink (namestring output) (string-right-trim "/" (namestring link)))
      (rejects (lambda () (run-job input link generator :identity identity :pages '(1 2) :dpi 72 :resume t))
               "symlink job root rejected"))
    (let ((cli (docling:parse-conversion-arguments '("--input" "a.pdf" "--output" "out" "--pages" "1,3-5" "--device" "gpu" "--resume"))))
      (check (equal (getf cli :pages) '(1 3 4 5)) "bounded CLI range expansion")
      (check (eq (getf cli :device) :gpu) "explicit GPU")
      (check (getf cli :resume) "explicit resume flag"))
    (check (eq :help (docling:parse-conversion-arguments '("--help"))) "help without model")
    (dolist (arguments '(("--unknown") ("--input") ("--input" "a")
                         ("--input" "a" "--output" "b" "--input" "c")
                         ("--input" "a" "--output" "b" "--pages" "1-99999")
                         ("--input" "a" "--output" "b" "--pages" "1,1")
                         ("--input" "a" "--output" "b" "--pages" "2,1")
                         ("--input" "a" "--output" "b" "--pages" "1-2-3")
                         ("--input" "a" "--output" "b" "--pages" "#.(oops)")
                         ("--input" "a" "--output" "b" "--device" "cuda")
                         ("--input" "a" "--output" "b" "--dpi" "-1")
                         ("--input" "a" "--output" "b" "--max-new-tokens" "4097")))
      (rejects (lambda () (docling:parse-conversion-arguments arguments)) "invalid CLI rejected"))
    (sb-posix:mkdir (namestring (merge-pathnames ".lock/" output)) #o700)
    (rejects (lambda () (run-job input output generator :identity identity :pages '(1 2) :dpi 72 :resume t)) "concurrent/stale lock refused")
    (sb-posix:rmdir (namestring (merge-pathnames ".lock/" output)))
    (let ((metadata (merge-pathnames "page-1.sexp" output)))
      (with-open-file (s metadata :direction :output :if-exists :supersede)
        (write-string "#.(setf cl-docling-application-tests::*reader-executed* t)" s))
      (rejects (lambda () (run-job input output generator :identity identity :pages '(1 2) :dpi 72 :resume t)) "unsafe cache reader syntax rejected")
      (check (not *reader-executed*) "reader payload was not executed")
      (delete-file metadata)
      (sb-posix:symlink "/nonexistent-cl-docling-test-target" (namestring metadata))
      (setf calls nil)
      (rejects (lambda () (run-job input output generator :identity identity :pages '(1 2) :dpi 72 :resume t)) "dangling cache link rejected")
      (check (null calls) "unsafe cache rejected before inference"))
    (format t "~&PASS: ~D application checks (real Poppler, injected generators; no model quality claim).~%" *checks*)))
