(defpackage #:cl-docling-bundle-tests (:use #:cl) (:export #:run-tests))
(in-package #:cl-docling-bundle-tests)
(defvar *checks* 0)
(defun check (value label)
  (incf *checks*) (unless value (error "Check failed: ~A" label)))
(defun rejects (thunk label)
  (check (handler-case (progn (funcall thunk) nil) (docling:document-error () t)) label))
(defun write-bundle (pages path &rest options)
  (apply #'uiop:symbol-call :docling :write-document-bundle pages path options))
(defun output-directory ()
  (merge-pathnames (format nil "bundle-test-~D-~D/" (get-universal-time) (random 1000000000))
                   (asdf:system-relative-pathname "cl-docling" ".build/")))
(defun read-data (directory name)
  (with-open-file (in (merge-pathnames name directory) :external-format :utf-8)
    (let ((*read-eval* nil))
      (let ((data (read in)))
        (check (eq :eof (read in nil :eof)) "metadata contains exactly one form")
        data))))

(defun run-tests ()
  (let* ((*checks* 0)
         (raw "<doctag><text>Notes 日本語</text><page_footer>17</page_footer></doctag>")
         (page (docling:parse-doctags raw :page-number 27 :token-ids #(2 9 42) :stop-reason :eos))
         (bad (docling:parse-doctags "<doctag><chart>kept</chart></doctag>" :page-number 28 :stop-reason :length))
         (directory (output-directory)))
    (multiple-value-bind (path status) (write-bundle (list page) directory)
      (check (equal (truename directory) path) "returns created canonical directory")
      (check (eq :complete status) "complete export status"))
    (let ((manifest (read-data directory "manifest.sexp"))
          (metadata (read-data directory "page-27.sexp")))
      (check (= 1 (getf manifest :schema-version)) "versioned manifest")
      (check (not (search "#A(" (uiop:read-file-string (merge-pathnames "manifest.sexp" directory))))
             "manifest strings use ordinary readable syntax")
      (check (eq :complete (getf manifest :status)) "manifest complete")
      (check (equalp #(2 9 42) (getf metadata :token-ids)) "supplied token IDs exact")
      (check (eq :eos (getf metadata :stop-reason)) "real stop reason retained")
      (check (null (getf metadata :diagnostics)) "clean diagnostics retained")
      (check (string= raw (uiop:read-file-string (merge-pathnames "page-27.doctags" directory))) "raw Unicode exact")
      (check (string= (docling:documents-to-markdown (list page))
                      (uiop:read-file-string (merge-pathnames "document.md" directory))) "combined Markdown exact"))
    (rejects (lambda () (write-bundle (list page) directory)) "existing bundle never overwritten")
    (check (string= raw (uiop:read-file-string (merge-pathnames "page-27.doctags" directory))) "existing bytes preserved")
    (dolist (partial '(nil t))
      (let* ((path (output-directory))
             (status (nth-value 1 (write-bundle (list page bad) path :allow-partial partial)))
             (manifest (read-data path "manifest.sexp"))
             (metadata (read-data path "page-28.sexp")))
        (check (eq status (if partial :partial :blocked)) "distinct blocked/partial status")
        (check (eq status (getf manifest :status)) "manifest matches return status")
        (check (equal (mapcar (lambda (d) (list :code (docling:document-diagnostic-code d)
                                               :start (docling:document-diagnostic-start d)
                                               :message (docling:document-diagnostic-message d)))
                              (docling:parsed-document-diagnostics bad))
                      (getf metadata :diagnostics)) "every diagnostic code, offset and message saved")
        (check (string= (docling:parsed-document-raw bad)
                        (uiop:read-file-string (merge-pathnames "page-28.doctags" path))) "blocked raw retained")
        (if partial
            (check (zerop (search "> WARNING:" (uiop:read-file-string (merge-pathnames "document.md" path)))) "partial warning retained")
            (progn
              (check (not (probe-file (merge-pathnames "document.md" path))) "blocked bundle has no combined Markdown")
              (check (not (probe-file (merge-pathnames "page-27.md" path))) "blocked bundle has no misleading clean page Markdown")))))
    (dolist (options '((:max-pages 0) (:max-raw-characters 1) (:max-token-ids 2)
                       (:max-output-characters 1) (:max-output-characters 0)))
      (let ((path (output-directory)))
        (rejects (lambda () (apply #'write-bundle (list page) path options)) "preflight budget failure")
        (check (not (probe-file path)) "failed preflight creates no directory")))
    (dolist (pages (list nil (list bad page) (list page page) (vector page)))
      (let ((path (output-directory)))
        (rejects (lambda () (write-bundle pages path)) "invalid page input")
        (check (not (probe-file path)) "invalid input has no filesystem effects")))
    (let ((link (output-directory)))
      (sb-posix:symlink (namestring directory) (string-right-trim "/" (namestring link)))
      (rejects (lambda () (write-bundle (list page) link)) "existing symlink rejected"))
    (test-interrupted-bundle page)
    (test-real-bundle)
    (format t "~&PASS: ~D bundle checks (local artifacts, no inference).~%" *checks*)
    t))

(defun test-interrupted-bundle (page)
  (let* ((path (output-directory))
         (symbol (find-symbol "BUNDLE-PUBLISH-MANIFEST" :docling))
         (original (symbol-function symbol)))
    (unwind-protect
         (progn
           (setf (symbol-function symbol) (lambda (&rest args) (declare (ignore args)) (error "Injected publication failure")))
           (check (handler-case (progn (write-bundle (list page) path) nil) (error () t)) "publication error propagated")
           (check (probe-file (merge-pathnames "page-27.doctags" path)) "interrupted raw evidence retained")
           (check (not (probe-file (merge-pathnames "manifest.sexp" path))) "no completion marker on interrupted write"))
      (setf (symbol-function symbol) original))))

(defun test-real-bundle ()
  (let* ((root (asdf:system-source-directory "cl-docling"))
         (records (with-open-file (in (merge-pathnames "tests/fixtures/bundles/generation.sexp" root))
                    (let ((*read-eval* nil)) (read in))))
         (pages (loop for record in records for number = (getf record :page-number) collect
                  (docling:parse-doctags
                   (uiop:read-file-string (merge-pathnames
                     (format nil "tests/fixtures/public-pdf/results/native/page-~D.doctags" number) root))
                   :page-number number :stop-reason (getf record :stop-reason)
                   :token-ids (getf record :token-ids))))
         (path (output-directory)))
    (check (eq :complete (nth-value 1 (write-bundle pages path))) "real recorded pages export completely")
    (let ((manifest (read-data path "manifest.sexp")))
      (check (equal '(27 28) (mapcar (lambda (p) (getf p :page-number)) (getf manifest :pages))) "manifest preserves source page order")
      (check (string= "document.md" (getf manifest :markdown)) "manifest names combined Markdown"))
    (loop for record in records for page in pages for number = (getf record :page-number) do
      (let ((metadata (read-data path (format nil "page-~D.sexp" number))))
        (check (equalp (getf record :token-ids) (getf metadata :token-ids)) "all original public token IDs survive file round trip")
        (check (eq :eos (getf metadata :stop-reason)) "original public EOS retained")
        (check (null (getf metadata :diagnostics)) "current parser diagnostics are clean")
        (check (string= (docling:parsed-document-raw page)
                        (uiop:read-file-string (merge-pathnames (format nil "page-~D.doctags" number) path))) "original public raw output exact")
        (check (string= (uiop:read-file-string (merge-pathnames (format nil "tests/fixtures/footers/page-~D.md" number) root))
                        (uiop:read-file-string (merge-pathnames (format nil "page-~D.md" number) path))) "previously verified Markdown exact")))))
