(defpackage #:docling-training-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-training-tests)
(defvar *checks* 0)
(defun check (value label)
  (incf *checks*) (unless value (error "Document training: ~A" label)))
(defun close-arrays (a b &optional (atol 2e-6) (rtol 2e-4))
  (check (equal (array-dimensions a) (array-dimensions b)) "shape")
  (dotimes (i (array-total-size a))
    (check (<= (abs (- (row-major-aref a i) (row-major-aref b i)))
               (+ atol (* rtol (abs (row-major-aref b i))))) "reference value")))
(defun ints (tensor)
  (let* ((a (tb:tensor-array tensor)) (b (make-array (array-dimensions a))))
    (dotimes (i (array-total-size a) b) (setf (row-major-aref b i) (round (row-major-aref a i))))))
(defun rejected (thunk)
  (check (handler-case (progn (funcall thunk) nil)
           (tb:backend-error () t) (docling:layout-error () t)) "reject invalid request"))
(defun run-tests ()
  (setf *checks* 0)
  (let* ((root (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_TRAINING_FIXTURE")))
         (device (ecase (intern (string-upcase (or (uiop:getenv "TB_DEVICE") "cpu")) :keyword)
                   (:cpu :cpu) (:gpu :gpu)))
         (ref (yason:parse (uiop:read-file-string (merge-pathnames "reference.json" root)) :json-arrays-as-vectors t)))
    (tb:with-resource (backend (tb:make-backend :device device))
      (let ((baseline (getf (tb:backend-memory backend) :handles)))
        (tb:with-resource (model (docling:load-document-model (merge-pathnames "base/" root) :backend backend))
          (let ((data (tbk:load-weight-file (merge-pathnames "inputs.safetensors" root) backend)))
            (unwind-protect
                 (let* ((ids (ints (gethash "ids" data))) (labels (ints (gethash "labels" data)))
                        (mask (ints (gethash "mask" data)))
                        (frozen (mapcar (lambda (p) (cons (car p) (tb:tensor-array (cdr p)))) (tb:named-parameters model))))
                   (tb:with-resource (features (docling:document-image-features model (gethash "pixels" data)))
                     (close-arrays (tb:tensor-array features) (tb:tensor-array (gethash "features" data)) 2e-5 3e-4)
                     (docling:make-document-lora model :rank 2 :alpha 4 :seed 17)
                     (check (= 8 (length (docling:document-lora-parameters model))) "q/v only")
                     (rejected (lambda () (tb:save-pretrained model (merge-pathnames "must-not-drop-adapter/" root))))
                     (rejected (lambda () (docling:document-loss-and-gradients model ids features :labels ids :attention-mask mask)))
                     (let ((masked (alexandria:copy-array mask)))
                       (setf (aref masked 0 1) 0)
                       (rejected (lambda () (docling:document-loss-and-gradients model ids features :labels labels :attention-mask masked))))
                     (tb:with-resource (optimizer (tb:make-sgd :learning-rate 0.03))
                       (dotimes (step 3)
                         (let ((expected (tbk:load-weight-file (merge-pathnames (format nil "gradients-~D.safetensors" step) root) backend)))
                           (unwind-protect
                                (multiple-value-bind (loss gradients)
                                    (docling:document-loss-and-gradients model ids features :labels labels :attention-mask mask)
                                  (unwind-protect
                                       (progn
                                         (check (< (abs (- loss (aref (gethash "losses" ref) step))) 2e-5) "Python image loss")
                                         (check (= (length gradients) (hash-table-count expected)) "every gradient")
                                         (dolist (p gradients) (close-arrays (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) expected)))))
                                    (mapc (lambda (p) (tb:dispose (cdr p))) gradients)))
                             (tbk:dispose-weights expected)))
                         (when (zerop step)
                           (tb:with-resource (changed (tbk:with-backend (backend)
                                                       (tbk:retain (tbk:multiply features (tb:tensor-from-array backend #(-1.0))))))
                             (multiple-value-bind (loss gradients)
                                 (docling:document-loss-and-gradients model ids changed :labels labels :attention-mask mask)
                               (unwind-protect
                                    (check (< (abs (- loss (gethash "changed_loss" ref))) 2e-5) "visual signal affects answer")
                                 (mapc (lambda (p) (tb:dispose (cdr p))) gradients)))))
                         (check (< (abs (- (docling:document-train-step model optimizer ids features :labels labels :attention-mask mask)
                                          (aref (gethash "losses" ref) step))) 2e-5) "Python update trajectory"))
                       (let ((updated (tbk:load-weight-file (merge-pathnames "updated.safetensors" root) backend)))
                         (unwind-protect
                              (dolist (p (docling:document-lora-parameters model))
                                (close-arrays (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) updated))))
                           (tbk:dispose-weights updated)))
                       (let ((handles (getf (tb:backend-memory backend) :handles)))
                         (dotimes (i 5) (docling:document-train-step model optimizer ids features :labels labels :attention-mask mask))
                         (check (= handles (getf (tb:backend-memory backend) :handles)) "no retained temporary handles")))
                     (dolist (p frozen)
                       (close-arrays (cdr p) (tb:tensor-array (cdr (assoc (car p) (tb:named-parameters model) :test #'equal))) 0 0))))
              (tbk:dispose-weights data))))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "complete cleanup")))
    (format t "~&PASS: ~D image-conditioned LoRA checks on ~A.~%" *checks* device)))
