(in-package #:cl-docling-tests)

(defun document-rejects (thunk description)
  (check (handler-case (progn (funcall thunk) nil)
           (docling:document-error () t)) description))

(defun diagnostic-codes (document)
  (mapcar #'docling:document-diagnostic-code
          (docling:parsed-document-diagnostics document)))

(defun test-documents ()
  (let* ((raw " <doctag><section_header_level_1><loc_0><loc_1><loc_499><loc_20>Common Lisp</section_header_level_1><text>Build together.</text></doctag><end_of_utterance>")
         (ids (vector 7 8 9))
         (document (docling:parse-doctags raw :stop-reason :eos :token-ids ids :page-number 3))
         (heading (first (docling:parsed-document-elements document))))
    (check (string= raw (docling:parsed-document-raw document)) "exact raw DocTags retained")
    (check (equalp ids (docling:parsed-document-token-ids document)) "generation IDs retained")
    (setf (aref ids 0) 99)
    (check (= 7 (aref (docling:parsed-document-token-ids document) 0)) "IDs snapshotted")
    (check (eq :eos (docling:parsed-document-stop-reason document)) "stop reason retained")
    (check (= 3 (docling:parsed-document-page-number document)) "page reference retained")
    (check (null (diagnostic-codes document)) "supported complete document is clean")
    (check (eq :heading (docling:document-element-kind heading)) "heading kind")
    (check (= 1 (docling:document-element-level heading)) "heading level")
    (check (equal '(0 1 499 20) (docling:document-element-location heading)) "quantized LTRB retained")
    (check (string= "<section_header_level_1><loc_0><loc_1><loc_499><loc_20>Common Lisp</section_header_level_1>"
                    (subseq raw (docling:document-element-start heading)
                                (docling:document-element-end heading))) "source span")
    (check (string= (format nil "## Common Lisp~%~%Build together.~%")
                    (docling:document-to-markdown document)) "heading and paragraph Markdown"))
  (let ((document (docling:parse-doctags "<doctag><ordered_list><list_item>First</list_item><list_item>Second</list_item></ordered_list><unordered_list><list_item>Third</list_item></unordered_list></doctag>")))
    (check (null (diagnostic-codes document)) "flat grouped lists supported")
    (check (string= (format nil "1. First~%2. Second~%~%- Third~%")
                    (docling:document-to-markdown document)) "list Markdown"))
  (dolist (case '(("<doctag><text>cut" :unclosed-tag)
                  ("<doctag><text>x</title></doctag>" :mismatched-close)
                  ("<doctag><text>x</text></doctag><doctag></doctag>" :document-wrapper)
                  ("<text>x</text>" :document-wrapper)
                  ("<doctag><text>x</text></doctag>garbage" :outside-content)
                  ("<doctag><text>x</text></doctag><end_of_utterance><end_of_utterance>" :end-marker)
                  ("<end_of_utterance><doctag></doctag>" :end-marker)
                  ("<doctag><text><loc_500><loc_1><loc_2><loc_3>x</text></doctag>" :location)
                  ("<doctag><text><loc_1>x</text></doctag>" :location)
                  ("<doctag><text><loc_10><loc_20><loc_1><loc_2>x</text></doctag>" :location)
                  ("<doctag><text>x<loc_1><loc_2><loc_3><loc_4></text></doctag>" :location)
                  ("<doctag><text><loc_no>x</text></doctag>" :location)
                  ("<doctag><text>a<title>b</title>c</text></doctag>" :unsupported-structure)
                  ("<doctag><ordered_list><text>bad</text></ordered_list></doctag>" :unsupported-structure)
                  ("<doctag><ordered_list><list_item>A<unordered_list><list_item>B</list_item></unordered_list></list_item></ordered_list></doctag>" :unsupported-structure)
                  ("<doctag><chart>unsupported</chart></doctag>" :unsupported-tag)
                  ("<doctag><section_header_level_0>x</section_header_level_0></doctag>" :unsupported-tag)
                  ("<doctag><section_header_level_6>x</section_header_level_6></doctag>" :unsupported-tag)
                  ("<doctag><text>&lt;script&gt;</text></doctag>" :ambiguous-entity)
                  ("<doctag><text>x</text></doctag><" :malformed-token)))
    (let ((document (docling:parse-doctags (first case))))
      (check (member (second case) (diagnostic-codes document)) (format nil "diagnostic ~S" case))
      (check (string= (first case) (docling:parsed-document-raw document)) "invalid raw retained")
      (document-rejects (lambda () (docling:document-to-markdown document)) "strict export rejects diagnostics")
      (multiple-value-bind (markdown diagnostics) (docling:document-to-markdown document :allow-partial t)
        (check (search "WARNING" markdown) "partial output visibly marked")
        (check diagnostics "partial output returns diagnostics"))))
  (let ((document (docling:parse-doctags "<doctag><text>Complete looking</text></doctag>" :stop-reason :length)))
    (check (member :generation-truncated (diagnostic-codes document)) "length stop overrides balanced markup")
    (document-rejects (lambda () (docling:document-to-markdown document)) "truncated generation rejected"))
  (let ((document (docling:parse-doctags "<doctag><text># hi [x](url) *bold* & more</text></doctag>")))
    (check (string= (format nil "\\# hi \\[x\\]\\(url\\) \\*bold\\* &amp; more~%")
                    (docling:document-to-markdown document)) "text cannot inject Markdown"))
  (let ((document (docling:parse-doctags (format nil "<doctag><text>1. unintended list~%===</text></doctag>"))))
    (check (string= (format nil "1\\. unintended list~%\\=\\=\\=~%")
                    (docling:document-to-markdown document)) "numeric lists and setext headings escaped"))
  (let ((document (docling:parse-doctags (format nil "<doctag><unordered_list><list_item>one~%two</list_item></unordered_list></doctag>"))))
    (check (string= (format nil "- one~%  two~%") (docling:document-to-markdown document))
           "multiline list text remains indented within its item"))
  (test-pictures)
  (dolist (args '((:max-characters 5) (:max-nodes 1) (:max-depth 1)
                  (:max-depth 0) (:max-depth 129) (:page-number 0) (:stop-reason :invalid)
                  (:token-ids #(1 -1))))
    (document-rejects (lambda () (apply #'docling:parse-doctags "<doctag><text>x</text></doctag>" args))
                      (format nil "bounded/validated input ~S" args)))
  (let ((raw "<doctag><text><loc_1><loc_2><loc_3><loc_4>hello 日本語</text></doctag>"))
    (dotimes (length (length raw))
      (let ((document (docling:parse-doctags (subseq raw 0 length) :stop-reason :length)))
        (check (member :generation-truncated (diagnostic-codes document)) "every truncated prefix diagnosed")
        (document-rejects (lambda () (docling:document-to-markdown document)) "every truncated prefix blocks clean export"))))
  (test-document-oracle)
  (test-document-oracle "tests/fixtures/footers/")
  (test-page-footers)
  (test-public-footer-replay)
  (test-document-oracle "tests/fixtures/headers-footnotes/")
  (test-headers-footnotes))

(defun test-pictures ()
  (let* ((raw "<doctag><page_header>8</page_header><picture><loc_67><loc_77><loc_363><loc_178><other></picture><text>After.</text></doctag>")
         (document (docling:parse-doctags raw :stop-reason :eos))
         (picture (second (docling:parsed-document-elements document))))
    (check (null (diagnostic-codes document)) "location-only picture parses cleanly")
    (check (eq :picture (docling:document-element-kind picture)) "distinct picture kind")
    (check (equal '(67 77 363 178) (docling:document-element-location picture)) "picture coordinates")
    (check (eq :other (docling:document-element-classification picture)) "bounded picture classification")
    (check (string= "" (docling:document-element-text picture)) "picture invents no caption")
    (document-rejects (lambda () (docling:document-to-markdown document))
                      "picture cannot export without an explicit asset")
    (check (string= (format nil "8~%~%![Picture](assets/page-8-picture-1.png)~%~%After.~%")
                    (docling:document-to-markdown document
                      :picture-paths '("assets/page-8-picture-1.png")))
           "picture asset remains in reading order"))
  (dolist (case '(("<doctag><picture></picture></doctag>" :picture-location)
                  ("<doctag><picture><loc_1><loc_2><loc_3><loc_4>caption</picture></doctag>" :picture-content)
                  ("<doctag><picture><caption>invented</caption></picture></doctag>" :unsupported-structure)
                  ("<doctag><picture><loc_1><loc_2><loc_3><loc_4><other><signature></picture></doctag>" :picture-classification)
                  ("<doctag><picture><loc_3><loc_2><loc_1><loc_4></picture></doctag>" :location)))
    (let ((document (docling:parse-doctags (first case))))
      (check (member (second case) (diagnostic-codes document)) "invalid picture diagnosed")
      (document-rejects (lambda () (docling:document-to-markdown document :picture-paths '("assets/p.png")))
                        "invalid picture blocks strict export")))
  (let ((document (docling:parse-doctags "<doctag><picture><loc_1><loc_2><loc_3><loc_4></picture></doctag>")))
    (dolist (paths '(nil () ("../p.png") ("/p.png") ("assets/p.png" "assets/q.png") ("assets/p).png")))
      (document-rejects (lambda () (docling:document-to-markdown document :picture-paths paths))
                        "picture paths are exact, relative and injection-safe")))
  (let* ((raw "<doctag><picture><loc_10><loc_20><loc_10><loc_40></picture></doctag>")
         (document (docling:parse-doctags raw :stop-reason :eos)))
    (check (find :location (docling:parsed-document-diagnostics document)
                 :key #'docling:document-diagnostic-code)
           "zero-width picture is rejected")))

(defun test-document-oracle (&optional (path "tests/fixtures/doctags/"))
  (let ((directory (asdf:system-relative-pathname "cl-docling" path)))
    (with-open-file (stream (merge-pathnames "cases.sexp" directory))
      (let ((*read-eval* nil))
        (dolist (case (read stream))
          (let* ((raw (uiop:read-file-string (merge-pathnames (getf case :input) directory)))
                 (document (docling:parse-doctags raw))
                 (expected (uiop:read-file-string (merge-pathnames (getf case :markdown) directory))))
            (check (null (diagnostic-codes document)) "independent fixture is clean")
            (check (string= expected (docling:document-to-markdown document)) "exact independent Python Markdown")
            (check (equal (getf case :texts)
                          (loop for element in (docling:parsed-document-elements document)
                                append (if (member (docling:document-element-kind element) '(:ordered-list :unordered-list))
                                           (mapcar #'docling:document-element-text (docling:document-element-children element))
                                           (list (docling:document-element-text element)))))
                   "independent Python reading order and Unicode text")))))))

(defun test-page-footers ()
  (let ((document (docling:parse-doctags (format nil "<doctag><page_footer>First~%Second</page_footer></doctag>"))))
    (check (string= (format nil "First~%Second~%") (docling:document-to-markdown document))
           "multiline footer uses the existing soft-break policy"))
  (let* ((source "<page_footer><loc_0><loc_450><loc_499><loc_480>日本語 *notes* [x](url)</page_footer>")
         (raw (format nil "<doctag><text>Body</text>~A</doctag>" source))
         (document (docling:parse-doctags raw :page-number 27 :stop-reason :eos))
         (footer (second (docling:parsed-document-elements document))))
    (check (null (diagnostic-codes document)) "footer is a supported leaf")
    (check (eq :page-footer (docling:document-element-kind footer)) "distinct footer kind")
    (check (equal '(0 450 499 480) (docling:document-element-location footer)) "footer quantized coordinates")
    (check (string= "page_footer" (docling:document-element-tag footer)) "footer tag retained")
    (check (string= source (subseq raw (docling:document-element-start footer)
                                 (docling:document-element-end footer))) "footer character span retained")
    (check (string= (format nil "Body~%~%日本語 \\*notes\\* \\[x\\]\\(url\\)~%")
                    (docling:document-to-markdown document)) "footer content preserved and escaped"))
  (dolist (case '(("<doctag><page_footer>cut" :unclosed-tag)
                  ("<doctag><page_footer>x</text></doctag>" :mismatched-close)
                  ("<doctag><page_footer><loc_1>x</page_footer></doctag>" :location)
                  ("<doctag><page_footer><loc_0><loc_0><loc_500><loc_499>x</page_footer></doctag>" :location)
                  ("<doctag><page_footer><loc_10><loc_20><loc_1><loc_2>x</page_footer></doctag>" :location)
                  ("<doctag><page_footer>x<loc_0><loc_0><loc_1><loc_1></page_footer></doctag>" :location)
                  ("<doctag><page_footer><text>x</text></page_footer></doctag>" :unsupported-structure)
                  ("<doctag><ordered_list><page_footer>x</page_footer></ordered_list></doctag>" :unsupported-structure)
                  ("<doctag><page_footer>&lt;script&gt;</page_footer></doctag>" :ambiguous-entity)))
    (let ((document (docling:parse-doctags (first case))))
      (check (member (second case) (diagnostic-codes document)) "footer failures remain diagnosed")
      (check (string= (first case) (docling:parsed-document-raw document)) "failed footer raw retained")
      (document-rejects (lambda () (docling:document-to-markdown document)) "bad footer blocks strict export")))
  (let ((raw "<doctag><page_footer><loc_0><loc_450><loc_499><loc_480>Footer 日本語</page_footer></doctag>"))
    (loop for end from 0 to (length raw) do
      (let ((document (docling:parse-doctags (subseq raw 0 end) :stop-reason :length)))
        (check (member :generation-truncated (diagnostic-codes document)) "every footer prefix reports truncation")
        (document-rejects (lambda () (docling:document-to-markdown document)) "truncated footer blocks strict export")))))

(defun test-headers-footnotes ()
  (dolist (spec '(("page_header" :page-header) ("footnote" :footnote)))
    (destructuring-bind (tag kind) spec
      (let* ((source (format nil "<~A><loc_0><loc_1><loc_499><loc_20>日本語 *note* & x</~A>" tag tag))
             (raw (format nil "<doctag><text>Before</text>~A<text>After</text></doctag>" source))
             (document (docling:parse-doctags raw :stop-reason :eos :token-ids #(1 2)))
             (element (second (docling:parsed-document-elements document))))
        (check (null (diagnostic-codes document)) "new leaf has no diagnostics")
        (check (eq kind (docling:document-element-kind element)) "distinct semantic leaf kind")
        (check (string= tag (docling:document-element-tag element)) "original leaf tag")
        (check (equal '(0 1 499 20) (docling:document-element-location element)) "leaf coordinates")
        (check (string= raw (docling:parsed-document-raw document)) "unchanged leaf raw")
        (check (equalp #(1 2) (docling:parsed-document-token-ids document)) "unchanged leaf IDs")
        (check (string= source (subseq raw (docling:document-element-start element)
                                     (docling:document-element-end element))) "leaf source span")
        (check (string= (format nil "Before~%~%日本語 \\*note\\* &amp; x~%~%After~%")
                        (docling:document-to-markdown document)) "escaped leaf retained in source order"))
      (let ((document (docling:parse-doctags (format nil "<doctag><~A>First~%Second</~A></doctag>" tag tag))))
        (check (string= (format nil "First~%Second~%") (docling:document-to-markdown document))
               "new leaves retain existing soft-break policy"))
      (dolist (case '(("<loc_1>x" :location)
                      ("<loc_0><loc_0><loc_500><loc_499>x" :location)
                      ("<loc_10><loc_20><loc_1><loc_2>x" :location)
                      ("x<loc_0><loc_0><loc_1><loc_1>" :location)
                      ("<text>nested</text>" :unsupported-structure)
                      ("&lt;script&gt;" :ambiguous-entity)
                      ("<literal angle snippet>" :malformed-token)
                      ("<literal_snippet>" :unclosed-tag)))
        (let* ((raw (format nil "<doctag><~A>~A</~A></doctag>" tag (first case) tag))
               (document (docling:parse-doctags raw)))
          (check (member (second case) (diagnostic-codes document)) "new leaf does not weaken diagnostics")
          (check (string= raw (docling:parsed-document-raw document)) "invalid leaf raw retained")
          (document-rejects (lambda () (docling:document-to-markdown document)) "invalid leaf blocks export")))
      (let ((document (docling:parse-doctags (format nil "<doctag><~A>~C</~A></doctag>" tag (code-char 1) tag))))
        (check (member :control-character (diagnostic-codes document)) "leaf control characters diagnosed"))
      (let ((document (docling:parse-doctags (format nil "<doctag><ordered_list><~A>x</~A></ordered_list></doctag>" tag tag))))
        (check (member :unsupported-structure (diagnostic-codes document)) "leaf cannot become a list item"))
      (let ((raw (format nil "<doctag><~A>Note 日本語</~A></doctag>" tag tag)))
        (loop for end from 0 to (length raw) do
          (let ((document (docling:parse-doctags (subseq raw 0 end) :stop-reason :length)))
            (check (member :generation-truncated (diagnostic-codes document)) "every leaf prefix diagnoses truncation")
            (document-rejects (lambda () (docling:document-to-markdown document)) "truncated leaf blocks export")))))))

(defun test-public-footer-replay ()
  (let ((directory (asdf:system-relative-pathname "cl-docling" "tests/fixtures/footers/")))
    (with-open-file (in (merge-pathnames "replay.sexp" directory))
      (let ((*read-eval* nil))
        (dolist (case (read in))
          (let* ((page (getf case :page))
                 (raw (uiop:read-file-string
                       (asdf:system-relative-pathname "cl-docling"
                         (format nil "tests/fixtures/public-pdf/results/native/page-~D.doctags" page))))
                 (document (docling:parse-doctags raw :page-number page :stop-reason :eos))
                 (elements (docling:parsed-document-elements document))
                 (tables (remove-if-not (lambda (e) (eq :table (docling:document-element-kind e))) elements))
                 (footers (remove-if-not (lambda (e) (eq :page-footer (docling:document-element-kind e))) elements)))
            (check (null (diagnostic-codes document)) "recorded public page now parses without diagnostics")
            (check (string= raw (docling:parsed-document-raw document)) "original public DocTags retained exactly")
            (check (= page (docling:parsed-document-page-number document)) "physical page number retained")
            (check (equal (getf case :footers) (mapcar #'docling:document-element-text footers))
                   "independent Python footer text and order")
            (check (= 1 (length tables)) "exactly one original table")
            (check (equal (getf case :cells)
                          (mapcar (lambda (cell)
                                    (list (docling:table-cell-row-index cell) (docling:table-cell-column-index cell)
                                          (docling:table-cell-row-span cell) (docling:table-cell-column-span cell)
                                          (docling:table-cell-text cell)))
                                  (docling:document-table-cells (docling:document-element-table (first tables)))))
                   "every original cell, span and recognition error remains unchanged")
            (check (string= (uiop:read-file-string (merge-pathnames (format nil "page-~D.md" page) directory))
                            (docling:document-to-markdown document)) "complete saved footer-preserving Markdown replay")))))))
