(defpackage #:docling-image-generation-tests (:use #:cl))
(in-package #:docling-image-generation-tests)
(defvar *checks* 0)
(defvar *maxima* (make-hash-table :test 'equal))
(defun check (value message) (incf *checks*) (unless value (error "~A" message)))
(defun compare (a b atol rtol name)
  (check (equal (array-dimensions a) (array-dimensions b)) name)
  (let ((maximum 0f0))
    (dotimes (i (array-total-size a))
      (let* ((x (row-major-aref a i)) (y (row-major-aref b i)) (delta (abs (- x y))))
        (setf maximum (max maximum delta))
        (unless (<= delta (+ atol (* rtol (abs y)))) (error "~A at ~D: ~A vs ~A" name i x y))))
    (setf (gethash name *maxima*) maximum)
    (check t name) (format t "~&~A max error ~,8G~%" name maximum)))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil)
           (docling:layout-error () t) (tb:backend-error () t)) "Expected rejection"))
(defun last-logits (tensor)
  (let* ((array (tb:tensor-array tensor)) (vocab (array-dimension array 2))
         (out (make-array (list 1 1 vocab) :element-type 'single-float)))
    (dotimes (v vocab out) (setf (aref out 0 0 v) (aref array 0 (1- (array-dimension array 1)) v)))))
(defun reject-asset (model name mutate)
  (let* ((original (slot-value model 'docling::assets))
         (changed (docling::document-json-asset model name)))
    (funcall mutate changed)
    (unwind-protect
         (progn
           (setf (slot-value model 'docling::assets)
                 (acons name (babel:string-to-octets (with-output-to-string (s) (yason:encode changed s)) :encoding :utf-8)
                        (remove name original :key #'car :test #'equal)))
           (rejects (lambda () (docling::document-image-processor model))))
      (setf (slot-value model 'docling::assets) original))))
(let* ((dir (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_FIXTURE")))
       (manifest (docling::read-json-file (merge-pathnames "manifest.json" dir)))
       (device (ecase (intern (string-upcase (or (uiop:getenv "TB_DEVICE") "cpu")) :keyword)
                 (:cpu :cpu) (:gpu :gpu)))
       (real (eq (gethash "real" manifest) 'yason:true))
       (count (gethash "tiles" manifest)) (steps (length (gethash "tokens" manifest)))
       (atol (gethash "atol" manifest)) (rtol (gethash "rtol" manifest)))
  (tb:with-resource (backend (tb:make-backend :device device))
    (check (eq device (tb:backend-device backend)) "Requested device")
    (let ((baseline (getf (tb:backend-memory backend) :handles)))
      (tb:with-resource (model (docling:load-document-model (uiop:getenv "DOCLING_MODEL") :backend backend))
        (let ((ref (tbk:load-weight-file (merge-pathnames "reference.safetensors" dir) backend)))
          (unwind-protect
               (let* ((id-array (tb:tensor-array (gethash "input_ids" ref)))
                      (ids (make-array (array-dimensions id-array)))
                      (pixels (tb:tensor-array (gethash "pixels" ref))))
                 (dotimes (i (array-total-size ids)) (setf (row-major-aref ids i) (round (row-major-aref id-array i))))
                 (when real
                   (dolist (entry '(("preprocessor_config.json" "resample" 2)
                                    ("preprocessor_config.json" "do_resize" yason:false)
                                    ("preprocessor_config.json" "rescale_factor" 0.004d0)
                                    ("preprocessor_config.json" "unknown_policy" 1)
                                    ("processor_config.json" "image_seq_len" 63)
                                    ("chat_template.json" "chat_template" "unqualified template")
                                    ("tokenizer_config.json" "add_prefix_space" yason:true)))
                     (destructuring-bind (name key value) entry
                       (reject-asset model name (lambda (object) (setf (gethash key object) value)))))
                   (rejects (lambda () (docling:prepare-image-input model (merge-pathnames "page.png" dir) :task "extra <image>")))
                   (rejects (lambda () (docling:generate-image model (merge-pathnames "page.png" dir) :max-new-tokens -1)))
                   (multiple-value-bind (native-ids native-pixels tiles prompt)
                       (docling:prepare-image-input model (merge-pathnames "page.png" dir))
                     (check (= tiles count) "All tiles retained")
                     (check (equalp ids native-ids) "Exact Python processor token IDs")
                     (compare pixels native-pixels 0 0 "native-pixels")
                     (check (equal prompt (uiop:read-file-string (merge-pathnames "prompt.txt" dir))) "Exact chat expansion")
                     (setf pixels native-pixels ids native-ids)))
                 (tb:with-resource (exact (docling:merge-image-embeddings model ids (gethash "features" ref) :tile-count count))
                   (compare (tb:tensor-array exact) (tb:tensor-array (gethash "merged" ref)) 0 0 "exact-merge"))
                 (rejects (lambda () (docling:merge-image-embeddings model ids (gethash "features" ref))))
                 (dolist (bad '(0 18 1.5))
                   (rejects (lambda () (docling:merge-image-embeddings model ids (gethash "features" ref) :tile-count bad))))
                 (rejects (lambda () (docling:document-tile-features model (make-array '(2 1 3 8 8) :element-type 'single-float))))
                 (tb:with-resource (features (docling:document-tile-features model pixels))
                   (compare (tb:tensor-array features) (tb:tensor-array (gethash "features" ref)) atol rtol "features")
                   (tb:with-resource (merged (docling:merge-image-embeddings model ids features :tile-count count))
                     (compare (tb:tensor-array merged) (tb:tensor-array (gethash "merged" ref)) atol rtol "merged"))
                   (tb:with-resource (cache (tb:make-cache model))
                     (let ((next ids))
                       (dotimes (i steps)
                         (tb:with-resource (logits (docling:forward-document model next :cache cache
                                                    :tile-count (if (zerop i) count 1)
                                                    :image-features (when (zerop i) features)))
                           (compare (last-logits logits) (tb:tensor-array (gethash (format nil "step-~D" i) ref))
                                    atol rtol (format nil "step-~D" i))
                           (when (= i (1- steps)) (compare (last-logits logits) (tb:tensor-array (gethash "full-last" ref)) atol rtol "full-last")))
                         (check (= (+ (array-dimension ids 1) i) (tb:cache-length cache)) "Cache length")
                         (setf next (make-array '(1 1) :initial-element (aref (gethash "tokens" manifest) i)))))
                     (rejects (lambda () (docling:forward-document model #2A((1)) :cache cache :image-features features :tile-count count))))
                   (let ((before (getf (tb:backend-memory backend) :handles)))
                     (dotimes (repeat 2)
                       (multiple-value-bind (tokens reason)
                           (docling:generate-document model ids nil :image-features features :tile-count count :max-new-tokens steps :eos-token-id nil)
                         (check (equalp tokens (gethash "tokens" manifest)) "Greedy generated IDs")
                         (check (eq reason :length) "Truncation status")))
                     (check (= before (getf (tb:backend-memory backend) :handles)) "Generation handle baseline")))
                 (when real
                   (let ((original (symbol-function 'docling:document-image-features)) (encodes 0))
                     (unwind-protect
                          (progn
                            (setf (symbol-function 'docling:document-image-features)
                                  (lambda (&rest arguments) (incf encodes) (apply original arguments)))
                            (multiple-value-bind (raw tokens reason)
                                (docling:generate-image model (merge-pathnames "page.png" dir) :max-new-tokens (gethash "budget" manifest))
                              (check (equal raw (gethash "raw" manifest)) "High-level raw text")
                              (check (equalp tokens (gethash "tokens" manifest)) "High-level IDs")
                              (check (eq reason (if (eq (gethash "stopped_on_eos" manifest) 'yason:true) :eos :length)) "High-level stop reason"))
                            (check (= encodes count) "Encode each tile once, not during decode")
                            (multiple-value-bind (raw tokens reason)
                                (docling:generate-image model (merge-pathnames "page.png" dir) :max-new-tokens 0)
                              (check (and (equal raw "") (zerop (length tokens)) (eq reason :length)) "Zero budget"))
                            (rejects (lambda () (docling:generate-image model (merge-pathnames "page.png" dir) :max-new-tokens 8192)))
                            (check (= encodes count) "Budget preflight runs before vision"))
                       (setf (symbol-function 'docling:document-image-features) original)))))
            (tbk:dispose-weights ref))))
      (check (= baseline (getf (tb:backend-memory backend) :handles)) "Model/reference lifetime baseline")))
  (setf (gethash "checks" manifest) *checks* (gethash "max_absolute_error" manifest) *maxima*
        (gethash "native_device" manifest) (string-downcase device))
  (with-open-file (out (merge-pathnames (format nil "validation-~(~A~).json" device) dir)
                      :direction :output :if-exists :supersede)
    (yason:encode manifest out))
  (format t "~&PASS: ~D image-generation checks on ~A.~%" *checks* device))
