(defpackage #:cl-docling-image-tests (:use #:cl))
(in-package #:cl-docling-image-tests)
(defvar *checks* 0)
(defvar *compared-floats* 0)
(defun check (value description)
  (incf *checks*)
  (unless value (error "Check failed: ~A" description)))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil) (docling:layout-error () t))
         "reject unsupported/invalid input"))
(defun bytes (file)
  (with-open-file (in file :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length in) :element-type '(unsigned-byte 8))))
      (assert (= (length data) (read-sequence data in))) data)))
(defun exact-floats (array file)
  (incf *compared-floats* (array-total-size array))
  (let ((data (bytes file)))
    (check (= (length data) (* 4 (array-total-size array))) "reference byte count")
    (dotimes (i (array-total-size array))
      (let ((bits (loop for j below 4 sum (ash (aref data (+ (* i 4) j)) (* j 8)))))
        (unless (= bits (logand #xffffffff (sb-kernel:single-float-bits (row-major-aref array i))))
          (error "Float bits differ at ~D in ~A: native ~S, expected bits ~X"
                 i file (row-major-aref array i) bits))))
    (check t "every FP32 bit equals independent PIL reference")))
(let* ((dir (uiop:ensure-directory-pathname
             (or (uiop:getenv "DOCLING_PROCESSOR_FIXTURE")
                 (asdf:system-relative-pathname "cl-docling" "tests/fixtures/processor/"))))
       (manifest (yason:parse (uiop:read-file-string (merge-pathnames "manifest.json" dir))))
       (tile (gethash "tile" manifest)) (longest (gethash "longest" manifest))
       (seq (gethash "seq" manifest)))
  (check (null docling::*image-library*) "loading ASDF does not initialize native runtime")
  (dolist (case (gethash "cases" manifest))
    (let* ((name (gethash "name" case))
           (processor (docling:make-image-processor :tile-size tile :longest-edge longest
                         :image-seq-len seq :split-images (not (equal name "unsplit")))))
      (multiple-value-bind (pixels mask grids)
          (docling:preprocess-images processor (list (merge-pathnames (format nil "~A.png" name) dir)))
        (check (equal (array-dimensions pixels) (gethash "shape" case)) name)
        (check (equal grids (list (list (gethash "rows" case) (gethash "cols" case)))) "tile grid")
        (check (loop for i below (array-total-size mask) always (= 1 (row-major-aref mask i))) "real masks")
        (exact-floats pixels (merge-pathnames (format nil "~A.f32" name) dir))
        (check (equal (docling:image-prompt processor (caar grids) (cadar grids))
                      (uiop:read-file-string (merge-pathnames (format nil "~A.prompt" name) dir)))
               "exact image markers and whitespace")
        (multiple-value-bind (rgb) (docling:preprocess-images processor
                                    (list (merge-pathnames (format nil "~A-rgb.png" name) dir)))
          (check (equalp pixels rgb) "RGB conversion discards alpha; no compositing")))))
  (let ((processor (docling:make-image-processor :tile-size tile :longest-edge longest :image-seq-len seq)))
    (multiple-value-bind (pixels mask grids)
        (docling:preprocess-images processor
          (list (merge-pathnames "portrait.png" dir) (merge-pathnames "thin.png" dir)))
      (declare (ignore grids))
      (check (equal (array-dimensions pixels) (gethash "batch_shape" manifest)) "padded batch shape")
      (exact-floats pixels (merge-pathnames "batch.f32" dir))
      (check (equalp (bytes (merge-pathnames "batch.mask" dir))
                     (make-array (array-total-size mask) :element-type '(unsigned-byte 8) :displaced-to mask))
             "exact padded masks"))
    (rejects (lambda () (docling:preprocess-images processor nil)))
    (rejects (lambda () (docling:preprocess-images processor (list (merge-pathnames "missing.png" dir)))))
    (rejects (lambda () (docling:preprocess-images processor (list (merge-pathnames "manifest.json" dir)))))
    (rejects (lambda () (docling:preprocess-images processor (list (merge-pathnames "portrait.png" dir)) :max-output-bytes 1)))
    (rejects (lambda () (docling:image-prompt processor 0 1)))
    (rejects (lambda () (docling:image-prompt processor 5 4)))
    (rejects (lambda () (docling:preprocess-images processor (list (format nil "file~C.png" #\Null)))))
    (dolist (file '("unsupported-palette.png" "unsupported-16bit.png" "truncated.png" "bad-crc.png" "animated.png"))
      (rejects (lambda () (docling:preprocess-images processor
                            (list (merge-pathnames "portrait.png" dir) (merge-pathnames file dir)))))))
  (dolist (args '((:tile-size 0) (:longest-edge 0) (:tile-size 15 :longest-edge 64)
                   (:tile-size 1024) (:image-seq-len 0) (:split-images :yes)))
    (rejects (lambda () (apply #'docling:make-image-processor args))))
  (check (zerop (docling::%image-live-count)) "all success/error paths release native images")
  (format t "~&PASS: ~D native image processor checks; ~D exact FP32 comparisons (libpng ~A, ~A).~%"
          *checks* *compared-floats* (docling::%png-version) dir))
