(defpackage #:docling-model-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-model-tests)
(defvar *checks* 0)
(defvar *maxima*)
(defun check (value message)
  (incf *checks*) (unless value (error "~A" message)))
(defun compare (actual expected atol rtol name)
  (check (equal (array-dimensions actual) (array-dimensions expected)) "Shape mismatch")
  (let ((maximum 0.0))
    (dotimes (i (array-total-size actual))
      (let* ((a (row-major-aref actual i)) (b (row-major-aref expected i)) (delta (abs (- a b))))
        (setf maximum (max maximum delta))
        (check (<= delta (+ atol (* rtol (abs b)))) (format nil "~A at ~D: ~A vs ~A" name i a b))))
    (setf (gethash name *maxima*) maximum)
    (format t "~&~A max error ~,8G~%" name maximum)))
(defun integers (tensor)
  (let* ((values (tb:tensor-array tensor)) (out (make-array (array-dimensions values))))
    (dotimes (i (array-total-size out) out) (setf (row-major-aref out i) (round (row-major-aref values i))))))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil)
           (docling:layout-error () t) (tb:backend-error () t)) "Expected rejection"))
(defun run-tests ()
  (setf *checks* 0)
  (let* ((directory (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_FIXTURE")))
         (device (let ((name (or (uiop:getenv "TB_DEVICE") "cpu")))
                   (cond ((equal name "cpu") :cpu) ((equal name "gpu") :gpu)
                         (t (error "TB_DEVICE must be cpu or gpu")))))
         (manifest (docling::read-json-file (merge-pathnames "manifest.json" directory)))
         (atol (gethash "atol" manifest)) (rtol (gethash "rtol" manifest))
         (*maxima* (make-hash-table :test 'equal)))
    (tb:with-resource (backend (tb:make-backend :device device))
      (check (eq device (tb:backend-device backend)) "Actual device")
      (let ((baseline (getf (tb:backend-memory backend) :handles)))
        (when (uiop:directory-exists-p (merge-pathnames "invalid/" directory))
          (dolist (case '("unknown-text" "resampler" "qk-norm" "noise" "tie-policy" "missing-text" "wrong-shape" "extra-weight"))
            (rejects (lambda () (docling:load-document-model
                                (merge-pathnames (format nil "invalid/~A/" case) directory) :backend backend)))))
        (tb:with-resource (model (docling:load-document-model (or (uiop:getenv "DOCLING_MODEL") directory) :backend backend))
          (let ((ref (tbk:load-weight-file (merge-pathnames "reference.safetensors" directory) backend)))
            (unwind-protect
                 (let* ((ids (integers (gethash "input_ids" ref)))
                        (mask (integers (gethash "attention_mask" ref)))
                        (patch-mask (integers (gethash "patch_mask" ref)))
                        (pixels (gethash "pixels" ref)))
                   (check (= (gethash "weights" manifest) (length (tb:named-parameters model))) "Weight coverage")
                   (tb:with-resource (exact (docling:merge-image-embeddings model ids (gethash "features" ref)))
                     (compare (tb:tensor-array exact) (tb:tensor-array (gethash "merged" ref)) 0 0 "exact-merge"))
                   (tb:with-resource (features (docling:document-image-features model pixels :patch-mask patch-mask))
                     (tb:with-resource (merged (docling:merge-image-embeddings model ids features))
                       (compare (tb:tensor-array merged) (tb:tensor-array (gethash "merged" ref)) atol rtol "merged"))
                     (tb:with-resource (logits (docling:forward-document model ids :image-features features :attention-mask mask))
                       (compare (tb:tensor-array logits) (tb:tensor-array (gethash "logits" ref)) atol rtol "logits")))
                   (let ((invalid-mask (make-array (array-dimensions mask) :initial-element 1)))
                     (setf (aref invalid-mask 0 0) 0)
                     (rejects (lambda () (docling:forward-document model ids :image-features (gethash "features" ref)
                                                                 :attention-mask invalid-mask))))
                   (rejects (lambda () (docling:forward-document model ids)))
                   (rejects (lambda () (docling:merge-image-embeddings model #2A((1 2)) (gethash "features" ref))))
                   (let ((changed (make-array (array-dimensions ids))))
                     (dotimes (i (array-total-size ids)) (setf (row-major-aref changed i) (row-major-aref ids i)))
                     (setf (aref changed 0 0) (gethash "image_token_id" (docling::document-config model)))
                     (rejects (lambda () (docling:merge-image-embeddings model changed (gethash "features" ref)))))
                   (let* ((n (array-dimension ids 1))
                          (prompt (make-array (list 1 n)))
                          (shape (tb:tensor-shape pixels))
                          (host (tb:tensor-array pixels))
                          (one (make-array (cons 1 (rest shape)) :element-type 'single-float)))
                     (dotimes (i n) (setf (aref prompt 0 i) (aref ids 0 i)))
                     (dotimes (i (array-total-size one)) (setf (row-major-aref one i) (row-major-aref host i)))
                     (tb:with-resource (pixel (tb:tensor-from-array backend one))
                       (tb:with-resource (cache (tb:make-cache model))
                         (tb:with-resource (prefill (docling:forward-document model prompt :cache cache :pixels pixel))
                           (check (plusp (tb:cache-length cache)) "Prefill cache"))
                         (tb:with-resource (forced (docling:forward-document model
                                                     (make-array '(1 1) :initial-element
                                                                 (gethash "image_token_id" (docling::document-config model)))
                                                     :cache cache))
                           (compare (tb:tensor-array forced) (tb:tensor-array (gethash "forced-image-token" ref))
                                    atol rtol "forced-image-token")))
                       (tb:with-resource (cache (tb:make-cache model :growth-step 2))
                         (let ((next prompt))
                           (dotimes (step 8)
                             (tb:with-resource (logits (docling:forward-document model next :cache cache
                                                                        :pixels (when (zerop step) pixel)))
                               (let* ((all (tb:tensor-array logits)) (vocab (array-dimension all 2))
                                      (last (make-array (list 1 1 vocab) :element-type 'single-float)))
                                 (dotimes (i vocab) (setf (aref last 0 0 i) (aref all 0 (1- (array-dimension all 1)) i)))
                                 (compare last (tb:tensor-array (gethash (format nil "step-~D" step) ref)) atol rtol (format nil "step-~D" step))
                                 (compare last (tb:tensor-array (gethash (format nil "full-~D" step) ref)) atol rtol (format nil "full-~D" step)))
                               (tbk:with-backend (backend)
                                 (let ((token (tbk:greedy-token logits)))
                                   (check (= token (aref (gethash "tokens" manifest) step)) "Greedy token mismatch")
                                   (setf next (make-array '(1 1) :initial-element token)))))
                             (check (= (+ n step) (tb:cache-length cache)) "Cache length"))
                           (rejects (lambda () (docling:forward-document model next :cache cache :pixels pixel)))))
                       (let ((before (getf (tb:backend-memory backend) :handles)))
                         (dotimes (i 2)
                           (multiple-value-bind (tokens reason)
                               (docling:generate-document model prompt pixel :max-new-tokens 8 :eos-token-id nil)
                             (check (equalp tokens (gethash "tokens" manifest)) "Public generation tokens")
                             (check (eq reason :length) "Explicit truncation reason")
                             (when (gethash "raw_text" manifest)
                               (check (equal (tb:decode-tokens model tokens) (gethash "raw_text" manifest)) "Raw token decoding"))))
                         (multiple-value-bind (tokens reason)
                             (docling:generate-document model prompt pixel :max-new-tokens 8
                                                        :eos-token-id (aref (gethash "tokens" manifest) 0))
                           (check (= 1 (length tokens)) "EOS immediately stops")
                           (check (eq reason :eos) "EOS reason"))
                         (multiple-value-bind (tokens reason)
                             (docling:generate-document model prompt pixel :max-new-tokens 0)
                           (check (zerop (length tokens)) "Zero token budget")
                           (check (eq reason :length) "Zero token reason"))
                         (check (= before (getf (tb:backend-memory backend) :handles)) "Repeated request leak")))))
              (tbk:dispose-weights ref)))
          (when (uiop:getenv "DOCLING_EXPORT")
            (tb:save-pretrained model (uiop:getenv "DOCLING_EXPORT"))))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "Model lifetime leak")))
    (setf (gethash "checks" manifest) *checks* (gethash "native_device" manifest) (string-downcase device)
          (gethash "max_absolute_error" manifest) *maxima*)
    (with-open-file (s (merge-pathnames (format nil "validation-~(~A~).json" device) directory)
                       :direction :output :if-exists :supersede)
      (yason:encode manifest s))
    (format t "~&PASS: ~D native document-model checks on ~A.~%" *checks* device)))
