(in-package #:cl-docling-tests)

(defun combine-pages (pages &rest options)
  (apply #'uiop:symbol-call :docling :documents-to-markdown pages options))

(defun test-multipage ()
  (let* ((first (docling:parse-doctags "<doctag><text>First 日本語</text><page_footer>17</page_footer></doctag>"
                                        :page-number 27 :stop-reason :eos :token-ids #(1 2)))
         (second (docling:parse-doctags "<doctag><title>Next</title><text>Last</text></doctag>"
                                         :page-number 29 :stop-reason :eos))
         (pages (list first second))
         (expected (format nil "# Page 27~%~%First 日本語~%~%17~%~%---~%~%# Page 29~%~%# Next~%~%Last~%")))
    (multiple-value-bind (markdown reports) (combine-pages pages)
      (check (string= expected markdown) "explicit page boundaries, source order and selected-page gaps")
      (check (equal '((27) (29)) reports) "page-scoped diagnostics include clean pages")
      (check (string= markdown (combine-pages pages :allow-partial t)) "clean partial opt-in adds no warning")
      (check (string= expected (combine-pages pages :max-pages 2 :max-output-characters (length expected)))
             "exact resource boundaries accepted")
      (document-rejects (lambda () (combine-pages pages :max-output-characters (1- (length expected))))
                        "output character budget is exact")
      (document-rejects (lambda () (combine-pages pages :max-pages 1)) "page budget enforced"))
    (check (equalp #(1 2) (docling:parsed-document-token-ids first)) "composition retains token metadata")
    (check (string= "<doctag><text>First 日本語</text><page_footer>17</page_footer></doctag>"
                    (docling:parsed-document-raw first)) "composition does not rewrite raw output")
    (dolist (invalid (list nil (vector first second) (cons first second) (list :not-a-document)
                          (list second first) (list first first)))
      (document-rejects (lambda () (combine-pages invalid)) "invalid list, page or ordering rejected"))
    (let ((cycle (list first)))
      (setf (cdr cycle) cycle)
      (document-rejects (lambda () (combine-pages cycle)) "cyclic page list rejected"))
    (dolist (options '((:max-pages 0) (:max-pages 1.5) (:max-output-characters 0) (:max-output-characters "10")))
      (document-rejects (lambda () (apply #'combine-pages pages options)) "invalid resource bound rejected"))
    (let* ((bad (docling:parse-doctags "<doctag><text>cut" :page-number 30 :stop-reason :length))
           (mixed (list first second bad)))
      (document-rejects (lambda () (combine-pages mixed)) "late malformed page blocks entire strict export")
      (multiple-value-bind (markdown reports) (combine-pages mixed :allow-partial t)
        (check (zerop (search "> WARNING:" markdown)) "partial multi-page output has a global warning")
        (check (search "# Page 30" markdown) "partial page keeps its physical reference")
        (check (search "cut" markdown) "partial supported text retained")
        (check (equal '(27 29 30) (mapcar #'car reports)) "diagnostics mapped to every page")
        (check (equal (docling:parsed-document-diagnostics bad) (cdr (assoc 30 reports)))
               "original diagnostic objects and character offsets retained")
        (check (null (cdr (assoc 27 reports))) "clean page not assigned another page's error")
        (setf (cdr (assoc 30 reports)) nil)
        (check (docling:parsed-document-diagnostics bad) "report list mutation cannot erase source diagnostics")
        (document-rejects (lambda () (combine-pages mixed :allow-partial t :max-output-characters 10))
                          "partial mode does not bypass output budget")))
    (document-rejects (lambda () (combine-pages (list second first) :allow-partial t))
                      "partial mode never silently sorts invalid page order")
    (let ((empty (docling:parse-doctags "<doctag></doctag>" :page-number 1)))
      (check (string= (format nil "# Page 1~%~%") (combine-pages (list empty))) "empty page boundary retained")
      (check (eq :unknown (docling:parsed-document-stop-reason empty)) "unknown stop status not invented")))
  (let* ((pages (loop for page in '(27 28) collect
                  (docling:parse-doctags
                   (uiop:read-file-string (asdf:system-relative-pathname "cl-docling"
                     (format nil "tests/fixtures/public-pdf/results/native/page-~D.doctags" page)))
                   :page-number page :stop-reason :eos)))
         (markdown (combine-pages pages)))
    (check (string= (format nil "# Page 27~%~%~A~%---~%~%# Page 28~%~%~A"
                            (uiop:read-file-string (asdf:system-relative-pathname "cl-docling" "tests/fixtures/footers/page-27.md"))
                            (uiop:read-file-string (asdf:system-relative-pathname "cl-docling" "tests/fixtures/footers/page-28.md"))) markdown)
           "actual recorded pages retain exact previously checked Markdown bodies")))
