(defpackage #:docling-page-training-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-page-training-tests)
(defvar *checks* 0)
(defvar *errors* (make-hash-table :test 'equal))
(defun check (value label)
  (incf *checks*) (unless value (error "Page training: ~A" label)))
(defun close-arrays (actual expected name atol &optional (rtol 3e-4))
  (check (equal (array-dimensions actual) (array-dimensions expected))
         (list name :actual (array-dimensions actual) :expected (array-dimensions expected)))
  (let ((maximum 0.0))
    (dotimes (i (array-total-size actual))
      (let* ((ref (row-major-aref expected i)) (delta (abs (- (row-major-aref actual i) ref))))
        (setf maximum (max maximum delta))
        (check (<= delta (+ atol (* rtol (abs ref)))) (list name i delta ref))))
    (setf (gethash name *errors*) (max maximum (gethash name *errors* 0.0)))))
(defun rejected (function)
  (check (handler-case (progn (funcall function) nil)
           (docling:layout-error () t) (tb:backend-error () t)) "unsupported input rejected"))
(defun gradient-check (model backend root step ids labels mask features tiles reference)
  (let ((expected (tbk:load-weight-file (merge-pathnames (format nil "gradients-~D.safetensors" step) root) backend)))
    (unwind-protect
         (multiple-value-bind (loss gradients)
             (docling:document-loss-and-gradients model ids features :labels labels :attention-mask mask :tile-count tiles)
           (unwind-protect
                (progn
                  (close-arrays (vector loss) (vector (aref (gethash "losses" reference) step)) "loss" 1e-3 0)
                  (check (= 120 (length gradients) (hash-table-count expected)) "all q/v gradients")
                  (dolist (p gradients)
                    (close-arrays (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) expected)) "gradients" 2e-5 1e-3))
                  loss)
             (mapc (lambda (p) (tb:dispose (cdr p))) gradients)))
      (tbk:dispose-weights expected))))
(defun run-tests ()
  (let* ((root (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_PAGE_REFERENCE")))
         (destination (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_PAGE_OUTPUT")))
         (reference (yason:parse (uiop:read-file-string (merge-pathnames "reference.json" root)) :json-arrays-as-vectors t))
         (device (ecase (intern (string-upcase (or (uiop:getenv "TB_DEVICE") "cpu")) :keyword) (:cpu :cpu) (:gpu :gpu)))
         (losses nil))
    (when (probe-file destination) (error "Page output already exists: ~A" destination))
    (tb:with-resource (backend (tb:make-backend :device device))
      (let ((baseline (getf (tb:backend-memory backend) :handles)))
        (tb:with-resource (model (docling:load-document-model (uiop:getenv "DOCLING_MODEL") :backend backend))
          (let* ((frozen (mapcar (lambda (p) (cons (car p) (tb:tensor-array (cdr p)))) (tb:named-parameters model)))
                 (handles (getf (tb:backend-memory backend) :handles)) (feature-snapshot nil))
            (rejected (lambda () (docling:prepare-image-training-example model #P"/not-an-image.png" " ")))
            (check (= handles (getf (tb:backend-memory backend) :handles)) "failed preparation cleanup")
            ;; Enclosing scopes must not steal the returned owned feature handle.
            (multiple-value-bind (ids labels mask features tiles start)
                (tbk:with-backend (backend)
                  (docling:prepare-image-training-example model
                    (asdf:system-relative-pathname "cl-docling" (gethash "image" reference))
                    (gethash "answer" reference) :task (gethash "task" reference) :pad-to (gethash "length" reference)))
              (unwind-protect
                   (progn
                     (setf feature-snapshot (tb:tensor-array features))
                     (check (= 13 tiles) "all 13 visual tiles")
                     (check (= start (gethash "start" reference)) "exact answer boundary")
                     (let ((data (tbk:load-weight-file (merge-pathnames "inputs.safetensors" root) backend)))
                       (unwind-protect
                            (progn
                              (loop for a in (list ids labels mask) for name in '("ids" "labels" "mask") do
                                (close-arrays a (tb:tensor-array (gethash name data)) name 0 0))
                              (close-arrays (tb:tensor-array features) (tb:tensor-array (gethash "features" data)) "features" 1e-3))
                         (tbk:dispose-weights data)))
                     (docling:make-document-lora model :rank 2 :alpha 4 :seed 17)
                     (rejected (lambda () (docling:document-loss-and-gradients model ids features :labels labels :attention-mask mask)))
                     (rejected (lambda () (docling:document-loss-and-gradients model ids features :labels ids :attention-mask mask :tile-count tiles)))
                     (tb:with-resource (optimizer (tb:make-sgd :learning-rate (gethash "rate" reference)))
                       (dotimes (step 2)
                         (let ((handles (getf (tb:backend-memory backend) :handles)))
                           (push (gradient-check model backend root step ids labels mask features tiles reference) losses)
                           (close-arrays
                            (vector (docling:document-train-step model optimizer ids features :labels labels :attention-mask mask :tile-count tiles))
                            (vector (aref (gethash "losses" reference) step)) "update loss" 1e-3 0)
                           (check (= handles (getf (tb:backend-memory backend) :handles)) "step temporary cleanup")
                           (format t "~&Native ~A page step ~D: loss=~,8F~%" device step (first losses)))))
                     (let ((expected (tbk:load-weight-file (merge-pathnames "updated.safetensors" root) backend)))
                       (unwind-protect
                            (dolist (p (docling:document-lora-parameters model))
                              (close-arrays (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) expected)) "updated factors" 2e-6))
                         (tbk:dispose-weights expected)))
                     (let ((final (tbk:load-weight-file (merge-pathnames "final.safetensors" root) backend)))
                       (unwind-protect
                            (tb:with-resource (logits (docling:forward-document model ids :image-features features :attention-mask mask :tile-count tiles))
                              (tbk:with-backend (backend)
                                ;; JSON vectors may have spare capacity past their fill pointer.
                                (let* ((positions (gethash "selected" reference))
                                       (indices (tb:tensor-from-array backend
                                                  (make-array (length positions) :element-type '(signed-byte 32)
                                                              :initial-contents positions) :dtype :int32))
                                       (selected (tbk:take-indices logits indices 1)))
                                  (close-arrays (tb:tensor-array selected) (tb:tensor-array (gethash "logits" final)) "answer logits" 1e-3))))
                         (tbk:dispose-weights final)))
                     (dolist (p frozen)
                       (check (equalp (cdr p) (tb:tensor-array (cdr (assoc (car p) (tb:named-parameters model) :test #'equal)))) "base/vision/connector frozen exactly"))
                     (check (equalp feature-snapshot (tb:tensor-array features)) "borrowed image features unchanged")
                     (docling:save-document-adapter model destination))
                (tb:dispose features)))))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "all handles released")))
    (setf (gethash "device" *errors*) (string-downcase (symbol-name device))
          (gethash "losses" *errors*) (coerce (reverse losses) 'vector)
          (gethash "checks" *errors*) *checks*)
    (with-open-file (s (merge-pathnames "native-verification.json" destination) :direction :output :if-exists :error)
      (yason:encode *errors* s))
    (format t "~&PASS: ~D full-page training checks on ~A.~%" *checks* device)))
