(defpackage #:cl-docling-pdf-tests (:use #:cl) (:export #:run-tests))
(in-package #:cl-docling-pdf-tests)
(defvar *checks* 0)
(defun check (value label)
  (incf *checks*) (unless value (error "Check failed: ~A" label)))
(defun rejects (thunk label)
  (check (handler-case (progn (funcall thunk) nil) (docling:pdf-error () t)) label))
(defun fixture (name)
  (asdf:system-relative-pathname "cl-docling" (concatenate 'string "tests/fixtures/pdf/" name)))
(defun output-directory ()
  (merge-pathnames (format nil "pdf-test-~D-~D/" (get-universal-time) (random 1000000000))
                   (asdf:system-relative-pathname "cl-docling" ".build/")))

(defun run-tests ()
  (let ((*checks* 0))
    (test-page-size-labels)
    (let* ((directory (output-directory))
           (pages (docling:rasterize-pdf (fixture "native-pages.pdf") directory :pages '(2 1) :dpi 72)))
      (check (equal '(2 1) (mapcar #'docling:pdf-page-number pages)) "requested reading order")
      (check (equal '(90 0) (mapcar #'docling:pdf-page-rotation pages)) "rotation metadata")
      (dolist (page pages)
        (check (= 320 (docling:pdf-page-width page)) "rendered width")
        (check (= 448 (docling:pdf-page-height page)) "rendered height")
        (check (= 72 (docling:pdf-page-dpi page)) "explicit DPI")
        (check (probe-file (docling:pdf-page-pathname page)) "PNG exists"))
      (check (probe-file (merge-pathnames "manifest.sexp" directory)) "page manifest written")
      (with-open-file (out (asdf:system-relative-pathname "cl-docling" ".build/pdf-test-output.txt")
                           :direction :output :if-exists :supersede)
        (write-line (namestring directory) out))
      (rejects (lambda () (docling:rasterize-pdf (fixture "native-pages.pdf") directory)) "existing output directory never reused")
      (check (probe-file (docling:pdf-page-pathname (first pages))) "rejection preserves existing output"))
    (let ((page (first (docling:rasterize-pdf (fixture "native-pages.pdf") (output-directory) :pages '(1) :dpi 144))))
      (check (= 640 (docling:pdf-page-width page)) "DPI doubles width")
      (check (= 896 (docling:pdf-page-height page)) "DPI doubles height"))
    (dolist (args '((:pages nil) (:pages (0)) (:pages (1 1)) (:pages (3))
                    (:pages (1 2) :max-pages 1) (:dpi 0) (:dpi 301)
                    (:max-side 100) (:max-input-bytes 1) (:timeout-seconds 0)
                    (:pdfinfo "/no/such/pdfinfo")))
      (rejects (lambda () (apply #'docling:rasterize-pdf (fixture "native-pages.pdf") (output-directory) args))
               (format nil "invalid/bounded request ~S" args)))
    (rejects (lambda () (docling:rasterize-pdf (fixture "encrypted.pdf") (output-directory))) "encrypted input rejected")
    (rejects (lambda () (docling:rasterize-pdf (fixture "manifest.json") (output-directory))) "non PDF rejected")
    (rejects (lambda () (docling:rasterize-pdf (fixture "absent.pdf") (output-directory))) "missing input rejected")
    (let ((cycle (list 1)))
      (setf (cdr cycle) cycle)
      (rejects (lambda () (sb-ext:with-timeout 0.1
                           (docling:rasterize-pdf (fixture "native-pages.pdf") (output-directory) :pages cycle)))
               "circular page selection is rejected without unbounded traversal"))
    (test-process-lifetime)
    (test-process-cancellation)
    (format t "~&PASS: ~D PDF checks (Poppler process integration; no model-quality claim).~%" *checks*)
    t))

(defun test-page-size-labels ()
  (dolist (suffix '(" (letter)" " (A4)" ""))
    (check (equal '(612 792 0)
                  (multiple-value-list
                   (docling::pdf-page-geometry
                    (format nil "Page   27 size: 612 x 792 pts~A~%Page   27 rot: 0~%" suffix) 27)))
           "optional paper label does not change numeric dimensions"))
  (dolist (suffix '(" letter" " (letter" " (letter) trailing" " ()" " (foo/bar)"))
    (rejects (lambda () (docling::pdf-page-geometry
                         (format nil "Page 27 size: 612 x 792 pts~A~%Page 27 rot: 0~%" suffix) 27))
             "malformed or extra paper label metadata is rejected")))

(defun test-process-lifetime ()
  ;; Real TERM-ignoring child: timeout must escalate and be joined, not detached.
  (let* ((directory (output-directory))
         (start (get-internal-real-time)))
    (ensure-directories-exist directory)
    (rejects (lambda ()
               (handler-bind ((docling:pdf-error (lambda (condition) (format t "~&Expected timeout failure: ~A~%" condition))))
                 (docling::call-pdf-command
                  '("/bin/sh" "-c" "trap '' TERM; echo $$; exec sleep 30")
                  directory "slow" (+ start internal-time-units-per-second) "timeout")))
             "TERM-ignoring subprocess times out")
    (check (< (/ (- (get-internal-real-time) start) internal-time-units-per-second) 5)
           "timeout plus kill grace is bounded")
    (let* ((pid (parse-integer (string-trim '(#\Newline #\Space) (uiop:read-file-string (merge-pathnames "slow.out" directory)))))
           (state (uiop:run-program (list "ps" "-o" "stat=" "-p" (write-to-string pid)) :output :string :ignore-error-status t)))
      (check (or (zerop (length (string-trim '(#\Space #\Newline) state))) (find #\Z state))
             "owned child is gone or exited, not running"))))

(defun test-process-cancellation ()
  (let ((directory (output-directory)) (start (get-internal-real-time)))
    (ensure-directories-exist directory)
    (check (handler-case
               (sb-ext:with-timeout 0.25
                 (docling::call-pdf-command '("/bin/sh" "-c" "trap '' TERM; echo $$; exec sleep 30")
                                           directory "cancel" (+ start (* 30 internal-time-units-per-second)) "timeout")
                 nil)
             (sb-ext:timeout () t))
           "caller cancellation propagates after child cleanup")
    (check (< (/ (- (get-internal-real-time) start) internal-time-units-per-second) 5)
           "caller cancellation does not wait for original 30-second budget")
    (let* ((pid (parse-integer (string-trim '(#\Newline #\Space) (uiop:read-file-string (merge-pathnames "cancel.out" directory)))))
           (state (uiop:run-program (list "ps" "-o" "stat=" "-p" (write-to-string pid)) :output :string :ignore-error-status t)))
      (check (or (zerop (length (string-trim '(#\Space #\Newline) state))) (find #\Z state))
             "cancelled owned child has exited"))))
