(defpackage #:cl-docling-tests
  (:use #:cl)
  (:export #:run-tests))
(in-package #:cl-docling-tests)

(defvar *checks* 0)

(defun check (value description)
  (incf *checks*)
  (unless value (error "Check failed: ~A" description)))

(defun rejects (thunk description)
  (check (handler-case (progn (funcall thunk) nil)
           (docling:layout-error () t))
         description))

(defun counting-array (shape &optional (element-type t))
  (let ((result (make-array shape :element-type element-type)))
    (dotimes (i (array-total-size result) result)
      (setf (row-major-aref result i) i))))

(defun flat-values (array)
  (loop for i below (array-total-size array) collect (row-major-aref array i)))

(defun test-layout ()
  (let ((layout (docling:make-vision-layout)))
    (check (= 1024 (docling:patch-count layout)) "512/16 gives 1024 patches")
    (check (= 64 (docling:image-token-count layout)) "factor four gives 64 image tokens per tile")
    (check (= 12288 (docling:connector-input-width layout)) "projector input is 768*16")
    (check (= 576 (docling:vision-layout-text-hidden-size layout)) "decoder width"))
  (dolist (arguments '((:image-size 0) (:patch-size -1) (:channels 1.5)
                       (:hidden-size 0) (:num-heads 0) (:scale-factor 0)
                       (:text-hidden-size 0) (:image-size 511)
                       (:scale-factor 3) (:hidden-size 767)))
    (rejects (lambda () (apply #'docling:make-vision-layout arguments))
             (format nil "invalid layout ~S" arguments))))

(defun test-patchify ()
  (let* ((source (counting-array '(1 2 2 4) '(unsigned-byte 8)))
         (result (docling:patchify-image source 2)))
    (check (equal '(1 2 8) (array-dimensions result)) "patch shape")
    (check (equal '(0 1 4 5 8 9 12 13 2 3 6 7 10 11 14 15)
                  (flat-values result)) "patch order is channel, row, column")
    (check (equal (array-element-type source) (array-element-type result)) "preserve element type")
    (setf (row-major-aref result 0) 99)
    (check (zerop (row-major-aref source 0)) "patch output owns storage"))
  (rejects (lambda () (docling:patchify-image (make-array '(1 3 3 4)) 2)) "ragged patches")
  (rejects (lambda () (docling:patchify-image (make-array '(3 4 4)) 2)) "missing batch axis")
  (rejects (lambda () (docling:patchify-image (make-array '(0 3 4 4)) 2)) "empty batch")
  (rejects (lambda () (docling:patchify-image (make-array '(1 3 4 4)) 0)) "zero patch size"))

(defun test-shuffle ()
  (let* ((source (counting-array '(1 16 1)))
         (result (docling:pixel-shuffle-features source 2)))
    (check (equal '(1 4 4) (array-dimensions result)) "shuffle shape")
    (check (equal '(0 1 4 5 2 3 6 7 8 9 12 13 10 11 14 15)
                  (flat-values result)) "shuffle preserves local spatial order")
    (setf (row-major-aref result 0) 99)
    (check (zerop (row-major-aref source 0)) "shuffle output owns storage"))
  (let ((source (counting-array '(2 4 3))))
    (check (equalp source (docling:pixel-shuffle-features source 1)) "factor one is identity"))
  (dolist (case '(((1 6 2) 2) ((1 9 2) 2) ((0 4 2) 2)
                  ((1 4 0) 2) ((1 4 2) 0) ((4 2) 2)))
    (rejects (lambda () (docling:pixel-shuffle-features (make-array (first case)) (second case)))
             (format nil "invalid shuffle ~S" case))))

(defun test-oracle ()
  (let ((path (asdf:system-relative-pathname "cl-docling" "tests/fixtures/geometry.sexp")))
    (with-open-file (stream path)
      (let* ((*read-eval* nil)
             (fixture (read stream nil nil)))
        (check (= 1 (getf fixture :schema-version)) "known fixture schema")
        (dolist (case (getf fixture :cases))
          (let* ((source (counting-array (getf case :input-shape)))
                 (result (ecase (getf case :operation)
                           (:patchify (docling:patchify-image source (getf case :factor)))
                           (:shuffle (docling:pixel-shuffle-features source (getf case :factor))))))
            (check (equal (getf case :output-shape) (array-dimensions result)) "oracle shape")
            (check (equal (getf case :values) (flat-values result)) "independent oracle values")))))))

(defun run-tests ()
  (let ((*checks* 0))
    (test-layout)
    (test-patchify)
    (test-shuffle)
    (test-oracle)
    (test-documents)
    (test-multipage)
    (test-tables)
    (test-supervision)
    (format t "~&PASS: ~D checks (host geometry, DocTags and supervision; no model or GPU qualification).~%" *checks*)
    t))
