(in-package #:cl-docling-tests)

(defun test-supervision ()
  ;; Resolve dynamically so the test demonstrates the initially absent API.
  (multiple-value-bind (symbol present) (find-symbol "MAKE-ANSWER-SUPERVISION" :docling)
    (check (and present (fboundp symbol)) "answer supervision API exists")
    (multiple-value-bind (ids labels mask)
        (funcall symbol #(1 9 9 2 4 5 7) 4 :vocab-size 10 :image-token-id 9 :eos-token-id 7 :pad-to 9)
      (check (equal '(1 9) (array-dimensions ids)) "single-row padded IDs")
      (check (equal '(1 9 9 2 4 5 7 7 7) (flat-values ids)) "padding may share EOS ID")
      (check (equal '(-100 -100 -100 -100 4 5 7 -100 -100) (flat-values labels)) "answer plus real EOS only")
      (check (equal '(1 1 1 1 1 1 1 0 0) (flat-values mask)) "prompt/image remain attended, pad does not")
      (check (equal '(3 4 5) (loop for i below 8 unless (= -100 (aref labels 0 (1+ i))) collect i))
             "first answer predicted from last prompt position; no double shift")))
  (let ((source (vector 7 9 2 4 7)))
    (multiple-value-bind (ids labels mask)
        (docling:make-answer-supervision source 3 :vocab-size 10 :image-token-id 9 :eos-token-id 7)
      (setf (aref source 3) 8)
      (check (= 4 (aref ids 0 3)) "input storage is copied")
      (setf (aref ids 0 3) 6)
      (check (= 4 (aref labels 0 3)) "label storage is independent")
      (check (equal '(-100 -100 -100 4 7) (flat-values labels)) "user EOS masked; assistant EOS supervised")
      (check (every (lambda (x) (= x 1)) (flat-values mask)) "unpadded attention includes image and prompt")))
  (dolist (case '((#(1 9 4 7) 0) (#(1 9 4 7) 3) (#(1 9 4 7) 1.5)
                  (#(1 9 4 7) 5) (#() 1) ((1 9 4 7) 2) ("text" 2)
                  (#(1 9 4 10) 2) (#(1 9 -1 7) 2) (#(1 9 4.5 7) 2)
                  (#(1 9 4 6) 2) (#(1 9 7 4 7) 2) (#(1 9 9 7) 2)
                  (#(1 9 4 7) 2 :pad-to 3) (#(1 9 4 7) 2 :pad-to 8193)
                  (#(1 9 4 7) 2 :pad-to 4.5) (#(1 9 4 7) 2 :pad-token-id -1)
                  (#(1 9 4 7) 2 :pad-to 6 :pad-token-id 9)
                  (#(1 9 4 7) 2 :max-length 3) (#(1 9 4 7) 2 :max-length 8193)))
    (rejects (lambda () (apply #'docling:make-answer-supervision (first case) (second case)
                               :vocab-size 10 :image-token-id 9 :eos-token-id 7 (cddr case)))
             (format nil "reject invalid supervision ~S" case)))
  (dolist (arguments '((:vocab-size 0 :image-token-id 9 :eos-token-id 7)
                       (:vocab-size 10 :image-token-id 7 :eos-token-id 7)
                       (:vocab-size 10 :image-token-id 10 :eos-token-id 7)
                       (:vocab-size 10 :image-token-id 9 :eos-token-id nil)))
    (rejects (lambda () (apply #'docling:make-answer-supervision #(1 9 4 7) 2 arguments)) "invalid vocabulary/special IDs"))
  (let ((tokens (make-array 8192 :initial-element 1)))
    (setf (aref tokens 0) 9 (aref tokens 8191) 7)
    (multiple-value-bind (ids labels) (docling:make-answer-supervision tokens 8190 :vocab-size 10 :image-token-id 9 :eos-token-id 7)
      (check (= 8192 (array-dimension ids 1)) "exact context cap accepted")
      (check (= 2 (count-if (lambda (label) (/= label -100)) (flat-values labels))) "context cap retains only answer/EOS labels")))
  (multiple-value-bind (ids labels) (docling:make-answer-supervision #(1 4 7) 1 :vocab-size 10 :image-token-id 9 :eos-token-id 7)
    (declare (ignore ids))
    (check (equal '(-100 4 7) (flat-values labels)) "minimal prompt/answer/EOS example"))
  (with-open-file (in (asdf:system-relative-pathname "cl-docling" "tests/fixtures/supervision/cases.sexp"))
    (let ((*read-eval* nil))
      (dolist (case (read in))
        (multiple-value-bind (ids labels mask)
            (docling:make-answer-supervision (coerce (subseq (getf case :ids) 0 (getf case :length)) 'vector)
                                             (getf case :prompt-length) :vocab-size (getf case :vocab-size)
                                             :image-token-id (getf case :image-token-id) :eos-token-id (getf case :eos-token-id)
                                             :pad-to (getf case :pad-to))
          (check (equal (getf case :ids) (flat-values ids)) "independent padded input IDs")
          (check (equal (getf case :labels) (flat-values labels)) "independent unshifted labels")
          (check (equal (getf case :mask) (flat-values mask)) "independent attention mask")
          (let ((selected (loop for i below (1- (array-dimension ids 1))
                                unless (= -100 (aref labels 0 (1+ i))) collect i)))
            (check (equal selected (getf case :selected)) "independent shifted logit positions")
            (check (equal (getf case :targets) (mapcar (lambda (i) (aref labels 0 (1+ i))) selected))
                   "independent shifted answer targets")))))))
