(in-package #:cl-docling-tests)

(defun table-document (body &rest arguments)
  (apply #'docling:parse-doctags (format nil "<doctag><otsl>~A</otsl></doctag>" body) arguments))

(defun test-tables ()
  (let ((doc (table-document "<fcel>Merged<lcel><nl>")))
    (check (null (diagnostic-codes doc)) "valid horizontal span is supported")
    (check (string= (format nil "<table>~%<tr><td colspan=\"2\">Merged</td></tr>~%</table>~%")
                    (docling:document-to-markdown doc)) "merged cells preserve spans in HTML"))
  (let* ((doc (table-document "<loc_1><loc_2><loc_100><loc_200><ched>Name<ched>Count<nl><fcel>Lisp< fcel>bad<nl>")))
    (check (diagnostic-codes doc) "malformed table marker cannot become clean output"))
  (let* ((raw "<doctag><otsl><loc_1><loc_2><loc_100><loc_200><ched>Name<ched>Count<nl><fcel>Lisp<ecel><nl></otsl></doctag>")
         (doc (docling:parse-doctags raw))
         (element (first (docling:parsed-document-elements doc)))
         (table (docling:document-element-table element))
         (rows (docling:document-table-rows table)))
    (check (null (diagnostic-codes doc)) "well-formed rectangular table")
    (check (eq :table (docling:document-element-kind element)) "table element")
    (check (equal '(1 2 100 200) (docling:document-element-location element)) "table location")
    (check (= 2 (docling:document-table-column-count table)) "column count")
    (check (equal '(("Name" "Count") ("Lisp" ""))
                  (mapcar (lambda (row) (mapcar #'docling:table-cell-text row)) rows)) "ordered cells with empty cell")
    (check (eq :column-header (docling:table-cell-kind (first (first rows)))) "column-header role retained")
    (check (eq :empty (docling:table-cell-kind (second (second rows)))) "empty-cell role retained")
    (check (string= "<fcel>Lisp" (subseq raw (docling:table-cell-start (first (second rows)))
                                               (docling:table-cell-end (first (second rows))))) "cell source span")
    (check (string= (format nil "| Name | Count |~%| --- | --- |~%| Lisp |  |~%")
                    (docling:document-to-markdown doc)) "compact GFM table"))
  (check (string= (format nil "|  |  |~%| --- | --- |~%| A | B |~%")
                  (docling:document-to-markdown (table-document "<fcel>A<fcel>B<nl>")))
         "headless table never promotes data to headers")
  (check (string= (format nil "|  |~%| --- |~%| x\\|y<br>\\*z\\* |~%")
                  (docling:document-to-markdown (table-document (format nil "<fcel>x|y~%*z*<nl>"))))
         "pipe, markup and line break stay within a cell")
  (check (string= (format nil "| H |~%| --- |~%")
                  (docling:document-to-markdown (table-document "<ched>H<nl>"))) "header-only table")
  (check (string= (format nil "|  |~%| --- |~%| one<br>two |~%")
                  (docling:document-to-markdown (table-document (format nil "<fcel>one~C~Ctwo<nl>" #\Return #\Newline))))
         "CRLF is one cell break")
  (let ((doc (docling:parse-doctags "<doctag><text>Before</text><otsl><fcel>A<nl></otsl><text>After</text><otsl><ecel><ecel><nl></otsl></doctag>")))
    (check (null (diagnostic-codes doc)) "multiple tables and prose are independent")
    (check (equal '(:text :table :text :table)
                  (mapcar #'docling:document-element-kind (docling:parsed-document-elements doc))) "table/prose reading order"))
  (dolist (case '(("" :table-shape) ("<nl>" :table-shape)
                  ("<fcel>A" :table-shape) ("<fcel>A<nl><nl>" :table-shape)
                  ("<fcel>A<fcel>B<nl><fcel>C<nl>" :table-shape)
                  ("text<fcel>A<nl>" :table-content)
                  ("<ecel>not empty<nl>" :table-content)
                  ("<fcel><nl>" :table-content)
                  ("<lcel><nl>" :table-span)
                  ("<ucel><nl>" :table-span) ("<xcel><nl>" :table-span)
                  ("<ched>A<fcel>B<nl>" :table-header)
                  ("<fcel>A<nl><ched>B<nl>" :table-header)
                  ("<rhed>A<nl>" :table-header) ("<srow>A<nl>" :table-header)
                  ("<fcel>A<caption>B</caption><nl>" :table-content)
                  ("<fcel>A<loc_1><nl>" :table-content)
                  ("<fcel>A</fcel><nl>" :mismatched-close)
                  ("<loc_999><fcel>A<nl>" :location)
                  ("<fcel>&lt;script&gt;<nl>" :ambiguous-entity)))
    (let ((doc (table-document (first case))))
      (check (member (second case) (diagnostic-codes doc)) (format nil "table diagnostic ~S" case))
      (document-rejects (lambda () (docling:document-to-markdown doc)) "invalid table blocks normal export")
      (check (search "[Unsupported table; see raw DocTags.]"
                     (docling:document-to-markdown doc :allow-partial t)) "invalid table never renders misleading partial grid")))
  (let ((raw "<doctag><otsl><fcel>Data<nl></otsl></doctag>"))
    (dotimes (end (length raw))
      (let ((doc (docling:parse-doctags (subseq raw 0 end) :stop-reason :length)))
        (check (string= (subseq raw 0 end) (docling:parsed-document-raw doc)) "every table prefix preserved")
        (document-rejects (lambda () (docling:document-to-markdown doc)) "every table prefix blocks clean export"))))
  (document-rejects (lambda () (table-document (format nil "~{~A~}<nl>" (make-list 129 :initial-element "<ecel>"))))
                    "fixed column budget")
  (document-rejects (lambda () (table-document (format nil "~{~A~}" (make-list 4097 :initial-element "<ecel><nl>"))))
                    "fixed cell budget")
  (test-table-oracle)
  (test-merged-tables)
  (test-table-recognition-replay))

(defun test-table-recognition-replay ()
  ;; Frozen live outputs, independently token-matched with Transformers.
  (let* ((root (asdf:system-relative-pathname "cl-docling" "tests/fixtures/table-recognition/metal/"))
         (grid (docling:parse-doctags (uiop:read-file-string (merge-pathnames "grid.doctags" root)) :stop-reason :eos))
         (merged (docling:parse-doctags (uiop:read-file-string (merge-pathnames "merged.doctags" root)) :stop-reason :eos)))
    (check (null (diagnostic-codes grid)) "actual grid output is clean")
    (check (= 1 (length (docling:parsed-document-elements grid))) "actual grid is one table")
    (check (= 12 (length (docling:document-table-cells (docling:document-element-table
                                                     (first (docling:parsed-document-elements grid)))))) "actual grid retains 12 cells")
    (check (string= (uiop:read-file-string (merge-pathnames "grid.md" root))
                    (docling:document-to-markdown grid)) "actual grid Markdown replay is exact")
    (check (equal '(:table-shape :table-shape :table-shape) (diagnostic-codes merged)) "actual missing merge marker remains diagnosed")
    (check (not (docling:document-table-renderable-p (docling:document-element-table
                                                    (first (docling:parsed-document-elements merged))))) "actual ragged grid cannot render")
    (document-rejects (lambda () (docling:document-to-markdown merged)) "EOS is not proof of valid table structure")
    (check (search "[Unsupported table; see raw DocTags.]" (docling:document-to-markdown merged :allow-partial t))
           "real model failure stays an explicit placeholder")))

(defun test-merged-tables ()
  (let* ((raw "<doctag><otsl><fcel>A<lcel><nl><ucel><xcel><nl></otsl></doctag>")
         (doc (docling:parse-doctags raw))
         (table (docling:document-element-table (first (docling:parsed-document-elements doc))))
         (cell (first (docling:document-table-cells table))))
    (check (null (diagnostic-codes doc)) "two-dimensional span is valid")
    (check (equal '(2 2) (list (docling:table-cell-row-span cell) (docling:table-cell-column-span cell))) "anchor retains both spans")
    (check (equal '(("fcel" "lcel") ("ucel" "xcel"))
                  (mapcar (lambda (row) (mapcar #'docling:table-cell-tag row)) (docling:document-table-rows table))) "grid retains marker identities")
    (check (zerop (docling:table-cell-row-span (second (first (docling:document-table-rows table))))) "continuation slot is not an anchor")
    (check (string= "<fcel>A" (subseq raw (docling:table-cell-start cell) (docling:table-cell-end cell))) "resolved anchor preserves source span")
    (check (string= (format nil "<table>~%<tr><td rowspan=\"2\" colspan=\"2\">A</td></tr>~%<tr></tr>~%</table>~%")
                    (docling:document-to-markdown doc)) "all-continuation row retained in HTML")
    (dotimes (end (length raw))
      (let ((prefix (subseq raw 0 end)))
        (document-rejects (lambda () (docling:document-to-markdown (docling:parse-doctags prefix :stop-reason :length)))
                          "every merged prefix blocks strict output"))))
  (dolist (case '(("<fcel>A<lcel><nl><ucel><fcel>B<nl>" :table-span)
                  ("<fcel>A<fcel>B<nl><ucel><xcel><nl>" :table-span)
                  ("<fcel>A<lcel><nl><ucel><lcel><nl>" :table-span)
                  ("<fcel>A<lcel><nl><fcel>B<ucel><nl>" :table-span)
                  ("<fcel>A<xcel><nl>" :table-span)
                  ("<fcel>A<ucel><nl>" :table-span)
                  ("<fcel>A<nl><lcel><nl>" :table-span)
                  ("<fcel>A<lcel>hidden text<nl>" :table-content)
                  ("<ched>H<lcel><nl><ucel><xcel><nl>" :table-header)
                  ("<ched>H<lcel><fcel>Mixed<nl>" :table-header)
                  ("<fcel>A<lcel><nl><ched>H<lcel><nl>" :table-header)
                  ("<fcel><script>alert(1)</script><lcel><nl>" :table-content)
                  ("<fcel>&lt;script&gt;<lcel><nl>" :ambiguous-entity)))
    (let ((doc (table-document (first case))))
      (check (member (second case) (diagnostic-codes doc)) "invalid span/header/content is diagnosed")
      (document-rejects (lambda () (docling:document-to-markdown doc)) "invalid merge blocks strict output")
      (let ((partial (docling:document-to-markdown doc :allow-partial t)))
        (check (search "[Unsupported table; see raw DocTags.]" partial) "invalid merge keeps placeholder")
        (check (not (search "<table>" partial)) "partial output never invents a merged grid"))))
  (check (string= "&lt;script&gt;&amp;&quot;&#39;" (cl-docling::html-table-cell-text "<script>&\"'")) "HTML text escaping is not Markdown escaping")
  (let ((doc (table-document (format nil "<fcel>A~C~CB<lcel><nl>" #\Return #\Newline))))
    (check (search ">A<br>B</td>" (docling:document-to-markdown doc)) "merged CRLF renders one break"))
  (let* ((body (with-output-to-string (out)
                 (dotimes (r 32)
                   (dotimes (c 128)
                     (write-string (cond ((and (zerop r) (zerop c)) "<fcel>Maximum")
                                         ((zerop r) "<lcel>") ((zerop c) "<ucel>") (t "<xcel>")) out))
                   (write-string "<nl>" out))))
         (doc (table-document body))
         (cell (first (docling:document-table-cells (docling:document-element-table (first (docling:parsed-document-elements doc)))))))
    (check (null (diagnostic-codes doc)) "4096-slot merged grid is within budget")
    (check (equal '(32 128) (list (docling:table-cell-row-span cell) (docling:table-cell-column-span cell))) "maximum grid resolves one rectangle"))
  (with-open-file (in (asdf:system-relative-pathname "cl-docling" "tests/fixtures/merged-tables/cases.sexp"))
    (let ((*read-eval* nil))
      (dolist (case (read in))
        (let* ((doc (docling:parse-doctags (getf case :raw)))
               (table (docling:document-element-table (first (docling:parsed-document-elements doc)))))
          (check (null (diagnostic-codes doc)) "independent merged fixture clean")
          (check (= (getf case :rows) (length (docling:document-table-rows table))) "independent merged row count")
          (check (= (getf case :columns) (docling:document-table-column-count table)) "independent merged column count")
          (check (equal (getf case :cells)
                        (mapcar (lambda (cell) (list (docling:table-cell-row-index cell) (docling:table-cell-column-index cell)
                                                    (docling:table-cell-row-span cell) (docling:table-cell-column-span cell)
                                                    (docling:table-cell-text cell))) (docling:document-table-cells table)))
                 "exact Python anchor coordinates, row/column spans and text"))))))

(defun test-table-oracle ()
  (with-open-file (in (asdf:system-relative-pathname "cl-docling" "tests/fixtures/tables/cases.sexp"))
    (let ((*read-eval* nil))
      (dolist (case (read in))
        (let* ((doc (docling:parse-doctags (getf case :raw)))
               (table (docling:document-element-table (first (docling:parsed-document-elements doc))))
               (rows (docling:document-table-rows table)))
          (check (null (diagnostic-codes doc)) "independent rectangular fixture clean")
          (check (= (getf case :rows) (length rows)) "independent row count")
          (check (= (getf case :columns) (docling:document-table-column-count table)) "independent column count")
          (check (equal (getf case :cells)
                        (loop for row in rows for r from 0 append
                          (loop for cell in row for c from 0 collect (list r c (docling:table-cell-text cell)))))
                 "exact Python cell coordinates/text"))))))
