(defpackage #:docling-resume-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-resume-tests)
(defvar *checks* 0)
(defun check (value label) (incf *checks*) (unless value (error "Resume: ~A" label)))
(defun rejected (function)
  (check (handler-case (progn (funcall function) nil)
           (tb:backend-error () t) (docling:layout-error () t)) "invalid checkpoint/options rejected"))
(defun optimizer (&optional (rate 0.0001))
  (if (equal (uiop:getenv "DOCLING_RESUME_OPTIMIZER") "sgd")
      (tb:make-sgd :learning-rate rate :momentum 0.8 :weight-decay 0.02)
      (tb:make-adamw :learning-rate rate :beta1 0.8 :beta2 0.95 :epsilon 1e-6 :weight-decay 0.02)))
(defun ints (tensor)
  (let* ((a (tb:tensor-array tensor)) (b (make-array (array-dimensions a))))
    (dotimes (i (array-total-size a) b) (setf (row-major-aref b i) (round (row-major-aref a i))))))
(defun call-with-example (model backend fixture function)
  (if (uiop:getenv "DOCLING_RESUME_REAL")
      (let ((ref (yason:parse (uiop:read-file-string (merge-pathnames "reference.json" fixture)))))
        (multiple-value-bind (ids labels mask features tiles)
            (docling:prepare-image-training-example model
              (asdf:system-relative-pathname "cl-docling" (gethash "image" ref)) (gethash "answer" ref)
              :task (gethash "task" ref) :pad-to (gethash "length" ref))
          (unwind-protect (funcall function ids labels mask features tiles) (tb:dispose features))))
      (let ((data (tbk:load-weight-file (merge-pathnames "inputs.safetensors" fixture) backend)))
        (unwind-protect
             (tb:with-resource (features (docling:document-image-features model (gethash "pixels" data)))
               (funcall function (ints (gethash "ids" data)) (ints (gethash "labels" data))
                        (ints (gethash "mask" data)) features 1))
          (tbk:dispose-weights data)))))
(defun run-tests ()
  (let* ((root (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_RESUME_OUTPUT")))
         (fixture (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_RESUME_FIXTURE")))
         (base (uiop:getenv "DOCLING_MODEL")) (phase (uiop:getenv "DOCLING_RESUME_PHASE"))
         (checkpoint (merge-pathnames "step-two/" root))
         (device (ecase (intern (string-upcase (uiop:getenv "TB_DEVICE")) :keyword) (:cpu :cpu) (:gpu :gpu)))
         (report (make-hash-table :test 'equal)))
    (tb:with-resource (backend (tb:make-backend :device device))
      (let ((baseline (getf (tb:backend-memory backend) :handles)) (model nil) (opt (optimizer)))
        (unwind-protect
             (progn
               (cond
                 ((equal phase "train")
                  (setf model (docling:load-document-model base :backend backend))
                  (docling:make-document-lora model :rank 2 :alpha 4 :seed 17)
                  (rejected (lambda () (docling:save-document-training-checkpoint model opt checkpoint)))
                  (check (not (probe-file checkpoint)) "unbound optimizer does not publish"))
                 ((equal phase "resume")
                  (unless (uiop:getenv "DOCLING_RESUME_REAL")
                    (dolist (path (uiop:subdirectories (merge-pathnames "invalid/" root)))
                      (rejected (lambda () (docling:load-document-training-checkpoint base path opt :backend backend)))
                      (check (= baseline (getf (tb:backend-memory backend) :handles)) "failed restore cleanup"))
                    (tb:with-resource (wrong (optimizer 0.01))
                      (rejected (lambda () (docling:load-document-training-checkpoint base checkpoint wrong :backend backend))))
                    (check (= baseline (getf (tb:backend-memory backend) :handles)) "mismatched optimizer cleanup"))
                  (multiple-value-bind (loaded step)
                      (tbk:with-backend (backend)
                        (docling:load-document-training-checkpoint base checkpoint opt :backend backend))
                    (setf model loaded) (check (= 2 step) "restored step count"))
                  (docling:save-document-training-checkpoint model opt (merge-pathnames "restored-before-step/" root))
                  (rejected (lambda () (docling:load-document-training-checkpoint base checkpoint opt :backend backend))))
                 ((equal phase "reset")
                  (setf model (docling:load-document-model base :backend backend))
                  (docling:load-document-adapter model (merge-pathnames "step-two-peft/" root)))
                 (t (error "Unknown phase")))
               (let ((frozen (mapcar (lambda (p) (cons (car p) (tb:tensor-array (cdr p)))) (tb:named-parameters model))))
                 (call-with-example model backend fixture
                   (lambda (ids labels mask features tiles)
                     (labels ((step-once ()
                                (docling:document-train-step model opt ids features :labels labels :attention-mask mask
                                                            :tile-count tiles :max-grad-norm 0.1)))
                       (when (equal phase "train")
                         (step-once) (step-once)
                         (docling:save-document-training-checkpoint model opt checkpoint)
                         (rejected (lambda () (docling:save-document-training-checkpoint model opt checkpoint)))
                         (docling:save-document-adapter model (merge-pathnames "step-two-peft/" root)))
                       (setf (gethash "loss" report) (step-once)))))
                 (dolist (p frozen)
                   (check (equalp (cdr p) (tb:tensor-array (cdr (assoc (car p) (tb:named-parameters model) :test #'equal)))) "base frozen")))
               (docling:save-document-training-checkpoint model opt (merge-pathnames (format nil "~A-final/" phase) root))
               (docling:save-document-adapter model (merge-pathnames (format nil "~A-peft/" phase) root)))
          (tb:dispose opt) (when model (tb:dispose model)))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "full cleanup")))
    (setf (gethash "checks" report) *checks*)
    (with-open-file (s (merge-pathnames (format nil "~A.json" phase) root) :direction :output :if-exists :error)
      (yason:encode report s))
    (format t "~&PASS: ~D ~A resume checks on ~A; next loss ~,9F.~%" *checks* phase device (gethash "loss" report))))
