(defpackage #:docling-training-input-tests (:use #:cl))
(in-package #:docling-training-input-tests)
(defvar *checks* 0)
(defun check (value message) (incf *checks*) (unless value (error "~A" message)))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil) (docling:layout-error () t)) "Expected input rejection"))
(multiple-value-bind (api present) (find-symbol "PREPARE-IMAGE-TRAINING-INPUT" :docling)
  (check (and present (fboundp api)) "Native image training-input API is absent")
  (let ((checkpoint (or (uiop:getenv "DOCLING_MODEL") (asdf:system-relative-pathname "cl-docling" ".build/smoldocling/"))))
    (tb:with-resource (model (docling:load-document-model checkpoint :device :cpu))
      (dolist (answer (list "" "   " "<image>" "<fake_token_around_image>" "<global-img>" "<row_1_col_1>"
                           "<|im_start|>" "<|im_end|>" "<end_of_utterance>" (string #\Null)))
        (rejects (lambda () (funcall api model #P"/not-a-page.png" answer))))
      (dolist (options '((:pad-to 1) (:pad-to 8193) (:pad-token-id -1)))
        (rejects (lambda () (apply api model (asdf:system-relative-pathname "cl-docling" "tests/fixtures/table-pages/grid.png")
                                  "<doctag><text>Answer</text></doctag>" options))))
      (with-open-file (in (asdf:system-relative-pathname "cl-docling" "tests/fixtures/supervision/cases.sexp"))
        (let ((*read-eval* nil))
          (dolist (case (read in))
            (multiple-value-bind (ids labels mask pixels tiles start)
                (funcall api model (asdf:system-relative-pathname "cl-docling" (getf case :image))
                         (getf case :answer) :task (getf case :task) :pad-to (getf case :pad-to))
              (dolist (entry (list (cons ids :ids) (cons labels :labels) (cons mask :mask)))
                (check (equal (getf case (cdr entry))
                              (loop for i below (array-total-size (car entry)) collect (row-major-aref (car entry) i)))
                       "Exact independent full IDs/labels/attention"))
              (check (= start (getf case :prompt-length)) "Exact prompt/answer boundary")
              (check (= tiles (getf case :tiles)) "All image tiles retained")
              (check (equal (array-dimensions pixels) (list 1 tiles 3 512 512)) "Training pixels retain pipeline axes")
              (check (= (* tiles 64) (loop for i below start count (= (getf case :image-token-id) (aref ids 0 i))))
                     "Every image placeholder is in the masked prompt")
              (check (equal (getf case :selected) (loop for i below (1- (array-dimension labels 1))
                                                       unless (= -100 (aref labels 0 (1+ i))) collect i))
                     "Native full tokenization supervises exact shifted positions")
              (format t "~&~A: ~D prompt tokens; ~D supervised tokens; ~D tiles.~%"
                      (getf case :name) start (- (getf case :length) start) tiles)))))))
  (format t "~&PASS: ~D training-input checks (tokenizer/processor only; no gradients or updates).~%" *checks*))
