(defpackage #:docling-vision-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-vision-tests)
(defvar *checks* 0)
(defun check (value message)
  (incf *checks*)
  (unless value (error "~A" message)))
(defun rejects (thunk)
  (check (handler-case (progn (funcall thunk) nil)
           (docling:layout-error () t) (tb:backend-error () t)) "Expected rejection"))

(defun check-isolation (model pixels mask backend)
  (let* ((host (tb:tensor-array pixels)) (shape (array-dimensions host))
         (size (third shape)) (side (array-dimension mask 1)) (patch (/ size side))
         (reference (tb:with-resource (value (docling:encode-vision model pixels :patch-mask mask :output :vision))
                      (tb:tensor-array value))))
    ;; Changing masked pixels must not influence valid patch outputs.
    (dotimes (channel (second shape))
      (dotimes (y size)
        (dotimes (x size)
          (when (zerop (aref mask 1 (floor y patch) (floor x patch)))
            (incf (aref host 1 channel y x) 100.0)))))
    (tb:with-resource (changed (tb:tensor-from-array backend host))
      (tb:with-resource (result (docling:encode-vision model changed :patch-mask mask :output :vision))
        (let ((actual (tb:tensor-array result)))
          (dotimes (b 2)
            (dotimes (y side)
              (dotimes (x side)
                (when (= 1 (aref mask b y x))
                  (dotimes (channel (array-dimension actual 2))
                    (check (< (abs (- (aref actual b (+ (* y side) x) channel)
                                     (aref reference b (+ (* y side) x) channel))) 2e-5)
                           "Padding isolation failure")))))))))
    ;; Change all of the second image; the first image must remain independent.
    (dotimes (i (/ (array-total-size host) 2))
      (setf (row-major-aref host (+ i (/ (array-total-size host) 2))) 0.25))
    (tb:with-resource (changed (tb:tensor-from-array backend host))
      (tb:with-resource (result (docling:encode-vision model changed :patch-mask mask :output :vision))
        (let ((actual (tb:tensor-array result)))
          (dotimes (i (/ (array-total-size actual) 2))
            (check (< (abs (- (row-major-aref actual i) (row-major-aref reference i))) 2e-5)
                   "Batch isolation failure")))))))
(defun run-tests ()
  (setf *checks* 0)
  (let* ((directory (uiop:ensure-directory-pathname
                     (or (uiop:getenv "DOCLING_FIXTURE") ".build/vision-tiny/")))
         (device (let ((name (or (uiop:getenv "TB_DEVICE") "cpu")))
                   (cond ((equal name "cpu") :cpu) ((equal name "gpu") :gpu)
                         (t (error "TB_DEVICE must be cpu or gpu")))))
         (manifest (with-open-file (s (merge-pathnames "manifest.json" directory)) (yason:parse s)))
         (atol (gethash "atol" manifest))
         (rtol (gethash "rtol" manifest))
         (maxima (make-hash-table :test 'equal)))
    (tb:with-resource (backend (tb:make-backend :device device))
      (check (eq device (tb:backend-device backend)) "Actual backend device")
      (let ((baseline (getf (tb:backend-memory backend) :handles)))
        (tb:with-resource (model (docling:load-vision-model (or (uiop:getenv "DOCLING_MODEL") directory) :backend backend))
          (check (= (gethash "weights" manifest) (docling:vision-weight-count model)) "Weight coverage")
          (let ((ref (tbk:load-weight-file (merge-pathnames "reference.safetensors" directory) backend)))
            (unwind-protect
                 (let ((pixels (gethash "pixels" ref)) (mask (tb:tensor-array (gethash "mask" ref))))
                   (let* ((expected (tb:tensor-array (gethash "positions" ref)))
                          (actual (docling::vision-mask-and-positions
                                   mask (array-dimension mask 0) (array-dimension mask 1))))
                     (check (equal (array-dimensions expected) (array-dimensions actual)) "Position shape")
                     (dotimes (i (array-total-size actual))
                       (check (= (row-major-aref expected i) (row-major-aref actual i)) "Exact position buckets")))
                   (rejects (lambda () (docling:encode-vision model pixels :output :invented)))
                   (rejects (lambda () (docling:encode-vision model pixels :patch-mask (make-array '(1 1 1)))))
                   (let ((invalid (make-array (array-dimensions mask) :initial-element 0)))
                     (rejects (lambda () (docling:encode-vision model pixels :patch-mask invalid)))
                     (fill-array invalid 1)
                     (setf (aref invalid 0 1 1) 0)
                     (rejects (lambda () (docling:encode-vision model pixels :patch-mask invalid)))
                     (setf (aref invalid 0 1 1) 2)
                     (rejects (lambda () (docling:encode-vision model pixels :patch-mask invalid))))
                   (when (uiop:directory-exists-p (merge-pathnames "invalid/" directory))
                     (dolist (case '("unknown-field" "unknown-root" "activation" "dropout" "missing-weight" "shape" "extra-weight"))
                       (rejects (lambda () (docling:load-vision-model
                                           (merge-pathnames (format nil "invalid/~A/" case) directory)
                                           :backend backend)))))
                   (dolist (stage '(:patch-projection :embeddings :first-layer :vision :shuffle :connector))
                     (tb:with-resource (actual (docling:encode-vision model pixels :patch-mask mask :output stage))
                       (let* ((expected (tb:tensor-array (gethash (string-downcase stage) ref)))
                              (values (tb:tensor-array actual)) (maximum 0.0))
                         (check (equal (array-dimensions expected) (array-dimensions values)) "Stage shape mismatch")
                         (dotimes (i (array-total-size expected))
                           (let* ((x (row-major-aref values i)) (y (row-major-aref expected i))
                                  (delta (abs (- x y))))
                             (setf maximum (max maximum delta))
                             (incf *checks*)
                             (unless (<= delta (+ atol (* rtol (abs y))))
                               (error "~A mismatch at ~D: ~A vs ~A" stage i x y))))
                         (setf (gethash (string-downcase stage) maxima) maximum)
                         (format t "~&~A max absolute error: ~,8G~%" stage maximum))))
                   (let ((before (getf (tb:backend-memory backend) :handles)))
                     (when (= 2 (first (tb:tensor-shape pixels)))
                       (check-isolation model pixels mask backend))
                     (dotimes (i 3)
                       (tb:with-resource (out (docling:encode-vision model pixels :patch-mask mask))
                         (check (plusp (array-total-size (tb:tensor-array out))) "Empty output")))
                     (check (= before (getf (tb:backend-memory backend) :handles)) "Request tensor leak")))
              (tbk:dispose-weights ref))))
        (check (= baseline (getf (tb:backend-memory backend) :handles)) "Model tensor leak")))
    (with-open-file (stream (merge-pathnames (format nil "validation-~(~A~).json" device) directory)
                            :direction :output :if-exists :supersede)
      (setf (gethash "native_device" manifest) (string-downcase device)
            (gethash "checks" manifest) *checks* (gethash "max_absolute_error" manifest) maxima)
      (yason:encode manifest stream))
    (format t "~&PASS: ~D native vision checks on ~A.~%" *checks* device)))

(defun fill-array (array value)
  (dotimes (i (array-total-size array)) (setf (row-major-aref array i) value)))
