(defpackage #:docling-lifetime-tests (:use #:cl) (:export #:run-tests))
(in-package #:docling-lifetime-tests)
(defvar *checks* 0)
(define-condition injected-failure (error) ())
(defun check (value message)
  (incf *checks*) (unless value (error "~A" message)))
(defun handles (backend) (getf (tb:backend-memory backend) :handles))

(defun run-tests ()
  (setf *checks* 0)
  (let* ((directory (uiop:ensure-directory-pathname (uiop:getenv "DOCLING_FIXTURE")))
         (device (if (equal (uiop:getenv "TB_DEVICE") "gpu") :gpu :cpu)))
    (tb:with-resource (backend (tb:make-backend :device device))
      (let ((baseline (handles backend)))
        (tb:with-resource (model (docling:load-vision-model directory :backend backend))
          (let ((ref (tbk:load-weight-file (merge-pathnames "reference.safetensors" directory) backend)))
            (unwind-protect
                 (let* ((input (gethash "embeddings" ref))
                        (host-mask (tb:tensor-array (gethash "mask" ref)))
                        (additive (nth-value 1 (docling::vision-mask-and-positions
                                              host-mask (array-dimension host-mask 0) (array-dimension host-mask 1))))
                        (outer-baseline (handles backend)) (scoped nil) (retained nil))
                   (unwind-protect
                        (progn
                          (tbk:with-backend (backend)
                            (let* ((mask (tb:tensor-from-array backend additive)) (before (handles backend)))
                              (setf scoped (docling::vision-block model input mask 0))
                              (check (= (handles backend) (1+ before)) "Block must retain only its caller-scoped result")
                              ;; Evaluation occurs after the inner scope has ended.
                              (let ((actual (tb:tensor-array scoped)) (expected (tb:tensor-array (gethash "first-layer" ref))))
                                (dotimes (i (array-total-size expected))
                                  (check (<= (abs (- (row-major-aref actual i) (row-major-aref expected i)))
                                             (+ 2e-5 (* 3e-4 (abs (row-major-aref expected i)))))
                                         "Lazy result differs from independent reference")))
                              (setf retained (tbk:retain scoped))
                              (let ((linear (symbol-function 'docling::vision-linear)) (before-error (handles backend)))
                                (unwind-protect
                                     (progn
                                       (setf (symbol-function 'docling::vision-linear)
                                             (lambda (m x prefix)
                                               (when (search "mlp.fc2" prefix) (error 'injected-failure))
                                               (funcall linear m x prefix)))
                                       (check (handler-case (progn (docling::vision-block model input mask 0) nil)
                                                (injected-failure () t)) "Expected injected graph failure"))
                                  (setf (symbol-function 'docling::vision-linear) linear))
                                (check (= before-error (handles backend)) "Failed block must release intermediates immediately"))))
                          (check (= (handles backend) (1+ outer-baseline)) "Only explicitly retained output escapes caller scope")
                          (check (handler-case (progn (tb:tensor-shape scoped) nil) (tb:backend-error () t))
                                 "Borrowed result must expire with caller scope")
                          (check (equal (tb:tensor-shape retained) (tb:tensor-shape input)) "Retained result survives outer scope"))
                     (when retained (tb:dispose retained)))
                   (check (= outer-baseline (handles backend)) "Result handle leak"))
              (tbk:dispose-weights ref))))
        (check (= baseline (handles backend)) "Model handle leak")))
    (format t "~&PASS: ~D vision lifetime checks on ~A.~%" *checks* device)))
