;;; All-tile frozen vision + initial decoder q/v gradients, no optimizer/update.
(load (merge-pathnames "experiment-common.lisp" *load-truename*))

(defun probe-json (file)
  (with-open-file (in file) (yason:parse in)))
(defun probe-time () (/ (get-internal-real-time) (float internal-time-units-per-second 1d0)))
(defun probe-close (actual expected atol rtol)
  (unless (equal (array-dimensions actual) (array-dimensions expected)) (error "Shape mismatch."))
  (let ((maximum 0d0))
    (dotimes (i (array-total-size actual))
      (let* ((a (row-major-aref actual i)) (b (row-major-aref expected i)) (delta (abs (- a b))))
        (unless (<= delta (+ atol (* rtol (abs b)))) (error "Numerical mismatch at ~D: ~A vs ~A" i a b))
        (setf maximum (max maximum delta))))
    maximum))
(defun probe-stage (backend start)
  (let ((memory (tb:backend-memory backend)))
    (experiment-object "seconds" (- (probe-time) start) "mlx_peak_bytes" (getf memory :peak)
                       "mlx_active_bytes" (getf memory :active) "mlx_cache_bytes" (getf memory :cache))))
(defun probe-snapshot (parameters)
  (mapcar (lambda (p) (cons (car p) (tb:tensor-array (cdr p)))) parameters))
(defun probe-unchanged (snapshot parameters)
  (unless (= (length snapshot) (length parameters)) (error "Parameter coverage changed."))
  (dolist (p parameters)
    (let ((old (assoc (car p) snapshot :test #'equal)))
      (unless (and old (equalp (cdr old) (tb:tensor-array (cdr p)))) (error "Parameter changed: ~A" (car p)))))
  t)

(defun probe-page (model backend inputs reference name expected policy frozen factors)
  (let ((handles (getf (tb:backend-memory backend) :handles)) (result nil))
    (multiple-value-bind (ids labels mask pixels tiles start)
        (docling:prepare-image-training-input model (merge-pathnames (format nil "~A.png" name) inputs)
          (uiop:read-file-string (merge-pathnames (format nil "~A.doctags" name) inputs) :external-format :utf-8))
      (declare (ignore start))
      (unless (and (= tiles (gethash "tiles" expected))
                   (= (array-dimension ids 1) (gethash "sequence_tokens" expected))) (error "Input budget changed."))
      (tb:reset-backend-peak-memory backend)
      (let ((begin (probe-time)))
        (tb:with-resource (features (docling:document-tile-features model pixels))
          (tbk:with-backend (backend) (tbk:evaluate features))
          (let ((vision-stage (probe-stage backend begin))
                (feature-copy (tb:tensor-array features)))
            (tb:reset-backend-peak-memory backend)
            (setf begin (probe-time))
            (multiple-value-bind (loss gradients)
                (docling:document-loss-and-gradients model ids features :labels labels :attention-mask mask :tile-count tiles)
              (unwind-protect
                   (progn
                     (tbk:with-backend (backend)
                       (dolist (p gradients) (tbk:evaluate (cdr p))))
                     (let ((gradient-stage (probe-stage backend begin))
                           (data (tbk:load-weight-file (merge-pathnames (format nil "~A-inputs.safetensors" name) reference) backend))
                           (oracle nil) (feature-error nil) (gradient-error 0d0))
                       (unwind-protect
                            (progn
                              (loop for array in (list ids labels mask) for key in '("ids" "labels" "mask")
                                    do (probe-close array (tb:tensor-array (gethash key data)) 0 0))
                              (setf feature-error (probe-close feature-copy (tb:tensor-array (gethash "features" data))
                                                              (gethash "features_atol" policy) (gethash "features_rtol" policy)))
                              (probe-close (vector loss) (vector (gethash "loss" expected)) (gethash "loss_atol" policy) 0)
                              (setf oracle (tbk:load-weight-file (merge-pathnames (format nil "~A-gradients.safetensors" name) reference) backend))
                              (unless (= (gethash "gradient_tensors" policy) (length gradients) (hash-table-count oracle))
                                (error "Incomplete gradient set."))
                              (dolist (p gradients)
                                (setf gradient-error (max gradient-error
                                  (probe-close (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) oracle))
                                               (gethash "gradients_atol" policy) (gethash "gradients_rtol" policy)))))
                              (unless (equalp feature-copy (tb:tensor-array features)) (error "Borrowed features changed."))
                              (probe-unchanged frozen (tb:named-parameters model))
                              (probe-unchanged factors (docling:document-lora-parameters model))
                              (setf result (experiment-object
                                "tiles" tiles "sequence_tokens" (array-dimension ids 1) "loss" loss
                                "gradient_tensors" (length gradients) "features" vision-stage "gradients" gradient-stage
                                "max_feature_error" feature-error "loss_error" (abs (- loss (gethash "loss" expected)))
                                "max_gradient_error" gradient-error "base_and_adapter_unchanged" yason:true "parity_passed" yason:true)))
                         (when oracle (tbk:dispose-weights oracle))
                         (tbk:dispose-weights data))))
                (mapc (lambda (p) (tb:dispose (cdr p))) gradients)))))))
    (unless (= handles (getf (tb:backend-memory backend) :handles)) (error "Page leaked handles."))
    (setf (gethash "handles_restored" result) yason:true)
    (format t "~&~A ~A: loss ~,7F; gradient peak ~D bytes.~%" (tb:backend-device backend) name
            (gethash "loss" result) (gethash "mlx_peak_bytes" (gethash "gradients" result)))
    (finish-output)
    result))

(destructuring-bind (input-path reference-path output) (uiop:command-line-arguments)
  (let* ((inputs (uiop:ensure-directory-pathname input-path))
         (reference (uiop:ensure-directory-pathname reference-path))
         (policy (probe-json (asdf:system-relative-pathname "cl-docling" "references/book-gradients.lock.json")))
         (oracle (probe-json (merge-pathnames "report.json" reference)))
         (device (ecase (intern (string-upcase (uiop:getenv "TB_DEVICE")) :keyword) (:cpu :cpu) (:gpu :gpu)))
         (cases (make-hash-table :test #'equal)) (remaining nil))
    (when (probe-file output) (error "Output must be new."))
    (tb:with-resource (backend (tb:make-backend :device device))
      (tb:with-resource (model (docling:load-document-model (uiop:getenv "DOCLING_MODEL") :backend backend))
        (docling:make-document-lora model :rank (gethash "rank" policy) :alpha (gethash "alpha" policy) :seed (gethash "seed" policy))
        (let ((initial (tbk:load-weight-file (merge-pathnames "initial.safetensors" reference) backend)))
          (unwind-protect
               (progn
                 (unless (= (hash-table-count initial) (length (docling:document-lora-parameters model)) 120)
                   (error "Initial factor coverage changed."))
                 (dolist (p (docling:document-lora-parameters model))
                   (probe-close (tb:tensor-array (cdr p)) (tb:tensor-array (gethash (car p) initial))
                                (gethash "initial_factors_atol" policy) (gethash "initial_factors_rtol" policy))))
            (tbk:dispose-weights initial)))
        ;; Deliberate test instrumentation: host snapshots count toward process RSS.
        (let ((frozen (probe-snapshot (tb:named-parameters model)))
              (factors (probe-snapshot (docling:document-lora-parameters model))))
          (dolist (name '("page-000" "page-002" "page-004"))
            (setf (gethash name cases)
                  (probe-page model backend inputs reference name (gethash name (gethash "cases" oracle)) policy frozen factors)))))
      (setf remaining (getf (tb:backend-memory backend) :handles))
      (unless (zerop remaining) (error "Model leaked handles.")))
    (experiment-write output (experiment-object "device" (string-downcase device) "updates" 0
                              "remaining_handles" remaining "sbcl" (lisp-implementation-version) "cases" cases) t)))
