;;; Frozen six-update real-book pilot; validation candidates only, never final data.
(load (merge-pathnames "experiment-common.lisp" *load-truename*))

(defun pilot-read (path) (with-open-file (in path) (yason:parse in)))
(defun pilot-time () (/ (get-internal-real-time) (float internal-time-units-per-second 1d0)))
(defun pilot-snapshot (parameters)
  (mapcar (lambda (parameter) (cons (car parameter) (tb:tensor-array (cdr parameter)))) parameters))
(defun pilot-equal (snapshot parameters)
  (and (= (length snapshot) (length parameters))
       (every (lambda (parameter)
                (let ((old (assoc (car parameter) snapshot :test #'equal)))
                  (and old (equalp (cdr old) (tb:tensor-array (cdr parameter)))))) parameters)))

(defun pilot-case (name)
  (experiment-object "name" name "split" "validation"))

(defun pilot-step (model optimizer backend inputs name step policy frozen)
  (let ((begin (pilot-time))
        (old (pilot-snapshot (docling:document-lora-parameters model)))
        (expected (gethash name (gethash "training_cases" policy))))
    (tb:reset-backend-peak-memory backend)
    (multiple-value-bind (ids labels mask pixels tiles start)
        (docling:prepare-image-training-input model
          (merge-pathnames (format nil "~A.png" name) inputs)
          (uiop:read-file-string (merge-pathnames (format nil "~A.doctags" name) inputs)
                                 :external-format :utf-8))
      (declare (ignore start))
      (unless (and (= tiles (gethash "tiles" expected))
                   (= (array-dimension ids 1) (gethash "sequence_tokens" expected)))
        (error "Complete training input changed."))
      (tb:with-resource (features (docling:document-tile-features model pixels))
        (let* ((loss (docling:document-train-step
                       model optimizer ids features :labels labels :attention-mask mask
                       :tile-count tiles :max-grad-norm
                       (gethash "max_grad_norm" (gethash "optimizer" policy))))
               (memory (tb:backend-memory backend))
               (record (experiment-object
                         "step" step "name" name "tiles" tiles
                         "sequence_tokens" (array-dimension ids 1) "loss" loss
                         "seconds" (- (pilot-time) begin) "mlx_peak_bytes" (getf memory :peak)
                         "mlx_active_bytes" (getf memory :active)
                         "mlx_cache_bytes" (getf memory :cache))))
          (setf (gethash "base_unchanged" record)
                (if (pilot-equal frozen (tb:named-parameters model)) yason:true yason:false)
                (gethash "adapter_changed" record)
                (if (pilot-equal old (docling:document-lora-parameters model)) yason:false yason:true)
                (gethash "handles" record) (getf (tb:backend-memory backend) :handles))
          record)))))

(destructuring-bind (input-path output-path) (uiop:command-line-arguments)
  (let* ((inputs (uiop:ensure-directory-pathname input-path))
         (output (uiop:ensure-directory-pathname output-path))
         (manifest (pilot-read (merge-pathnames "manifest.json" inputs)))
         (policy (pilot-read (asdf:system-relative-pathname "cl-docling" "references/book-finetune.lock.json")))
         (settings (gethash "optimizer" policy))
         (generation (gethash "generation" policy))
         (schedule (gethash "schedule" policy))
         (candidate-steps (coerce (gethash "candidate_steps" policy) 'list))
         (validation (map 'list #'pilot-case (gethash "validation_cases" manifest)))
         (steps nil) (remaining nil) (warm-handles nil))
    (when (probe-file output) (error "Training output must be new."))
    (ensure-directories-exist (merge-pathnames "placeholder" output))
    (when (some (lambda (name) (search "final" name)) (gethash "validation_cases" manifest))
      (error "Final cases are forbidden in the training process."))
    (tb:with-resource (backend (tb:make-backend :device :gpu))
      (unless (eq :gpu (tb:backend-device backend)) (error "Metal device required."))
      (let ((model nil)
            (optimizer (tb:make-adamw
                        :learning-rate (gethash "learning_rate" settings)
                        :beta1 (gethash "beta1" settings) :beta2 (gethash "beta2" settings)
                        :epsilon (gethash "epsilon" settings)
                        :weight-decay (gethash "weight_decay" settings))))
        (unwind-protect
             (progn
               (setf model (docling:load-document-model (uiop:getenv "DOCLING_MODEL") :backend backend))
               (docling:make-document-lora model :rank (gethash "rank" policy)
                                                :alpha (gethash "alpha" policy)
                                                :seed (gethash "seed" policy))
               (let ((frozen (pilot-snapshot (tb:named-parameters model))))
                 (loop for name in schedule for step from 1 do
                   (let ((record (pilot-step model optimizer backend inputs name step policy frozen)))
                     (unless warm-handles (setf warm-handles (gethash "handles" record)))
                     (unless (and (eq yason:true (gethash "base_unchanged" record))
                                  (eq yason:true (gethash "adapter_changed" record))
                                  (= warm-handles (gethash "handles" record))
                                  (<= (gethash "mlx_peak_bytes" record) (gethash "max_stage_mlx_bytes" policy))
                                  (<= (gethash "mlx_cache_bytes" record) (gethash "max_cache_bytes" policy)))
                       (error "Training input/base/resource gate failed."))
                     (push record steps)
                     (experiment-write (merge-pathnames (format nil "step-~D.json" step) output) record t)
                     (format t "~&Step ~D ~A: loss ~,8F.~%" step name (gethash "loss" record))
                     (finish-output)
                     (when (member step candidate-steps)
                       (docling:save-document-adapter model
                         (merge-pathnames (format nil "adapter-~D/" step) output))
                       (experiment-generate model validation inputs output
                                            (format nil "step-~D" step) :gpu generation))))))
          (tb:dispose optimizer)
          (when model (tb:dispose model))))
      (setf remaining (getf (tb:backend-memory backend) :handles))
      (unless (zerop remaining) (error "Final native handle leak.")))
    (experiment-write (merge-pathnames "training.json" output)
      (experiment-object "device" "gpu" "dtype" "float32" "final_step" (length schedule)
                         "remaining_handles" remaining "steps" (coerce (nreverse steps) 'vector)) t)))
