;;; Base-only development pages, including the unscorable illustration. No final data.
(load (merge-pathnames "experiment-common.lisp" *load-truename*))
(destructuring-bind (input-path destination) (uiop:command-line-arguments)
  (let* ((inputs (uiop:ensure-directory-pathname input-path)) (output (uiop:ensure-directory-pathname destination))
         (manifest (with-open-file (in (merge-pathnames "manifest.json" inputs)) (yason:parse in)))
         (cases (gethash "cases" manifest)) (protocol (gethash "protocol" manifest)))
    (unless (and (= 6 (length cases)) (every (lambda (c) (member (gethash "split" c) '("train" "validation") :test #'equal)) cases))
      (error "Expected six development-only cases."))
    (when (probe-file output) (error "Output must be new."))
    (ensure-directories-exist output)
    (tb:with-resource (backend (tb:make-backend :device :gpu))
      (unless (eq :gpu (tb:backend-device backend)) (error "Metal required."))
      (tb:with-resource (model (docling:load-document-model (uiop:getenv "DOCLING_MODEL") :backend backend))
        (dolist (case cases)
          (handler-case
              (experiment-generate model (list case) inputs output "base" :gpu (gethash "generation" protocol))
            (error (condition)
              (experiment-write (merge-pathnames (format nil "base/~A.error.json" (gethash "name" case)) output)
                                (experiment-object "error" (princ-to-string condition)) t)))))
      (unless (zerop (getf (tb:backend-memory backend) :handles)) (error "Native handles remain.")))
    (experiment-write (merge-pathnames "completion.json" output)
                      (experiment-object "remaining_handles" 0 "device" "gpu" "updates" 0) t)))
