"""Generate exact geometry references with PyTorch and Transformers, no downloads.

Usage: python scripts/generate-geometry-fixture.py --output PATH
Use --check PATH to verify a committed fixture without modifying it.
"""

import argparse
import hashlib
import inspect
import math
from pathlib import Path

import torch
import transformers
from transformers.models.idefics3.modeling_idefics3 import Idefics3Connector


def integers(values):
    return "(" + " ".join(str(int(value)) for value in values) + ")"


def generate():
    method = Idefics3Connector.pixel_shuffle
    digest = hashlib.sha256(inspect.getsource(method).encode()).hexdigest()
    cases = []
    specifications = [
        ("patchify", (2, 2, 4, 6), 2),
        ("patchify", (1, 3, 4, 4), 1),
        ("shuffle", (2, 16, 3), 2),
        ("shuffle", (1, 16, 2), 4),
        ("shuffle", (2, 4, 3), 1),
    ]
    for operation, shape, factor in specifications:
        source = torch.arange(math.prod(shape), dtype=torch.float32).reshape(shape)
        if operation == "patchify":
            result = torch.nn.functional.unfold(source, factor, stride=factor).transpose(1, 2)
        else:
            result = method(None, source, scale_factor=factor)
        cases.append(
            f"    (:operation :{operation} :input-shape {integers(shape)} :factor {factor}\n"
            f"     :output-shape {integers(result.shape)}\n"
            f"     :values {integers(result.flatten().tolist())})"
        )
    return (
        "; Generated by scripts/generate-geometry-fixture.py. Synthetic data only.\n"
        "(:schema-version 1\n"
        f' :torch-version "{torch.__version__}"\n'
        f' :transformers-version "{transformers.__version__}"\n'
        f' :connector-method-sha256 "{digest}"\n'
        " :cases (\n" + "\n".join(cases) + "))\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--output", type=Path)
    action.add_argument("--check", type=Path)
    args = parser.parse_args()
    content = generate()
    if args.check:
        if args.check.read_text() != content:
            raise SystemExit("FAIL: fixture differs (including reference version/provenance)")
        print("PASS: exact independent geometry fixture reproduction")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        # Exclusive creation prevents accidental replacement of reviewed fixtures.
        with args.output.open("x") as stream:
            stream.write(content)
        print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
