; Generated by scripts/generate-geometry-fixture.py. Synthetic data only.
(:schema-version 1
 :torch-version "2.14.0"
 :transformers-version "5.16.1"
 :connector-method-sha256 "59fd364af5e65d6c062e339968dee46e9c9c1812817003b80b475f5cdfdcede8"
 :cases (
    (:operation :patchify :input-shape (2 2 4 6) :factor 2
     :output-shape (2 6 8)
     :values (0 1 6 7 24 25 30 31 2 3 8 9 26 27 32 33 4 5 10 11 28 29 34 35 12 13 18 19 36 37 42 43 14 15 20 21 38 39 44 45 16 17 22 23 40 41 46 47 48 49 54 55 72 73 78 79 50 51 56 57 74 75 80 81 52 53 58 59 76 77 82 83 60 61 66 67 84 85 90 91 62 63 68 69 86 87 92 93 64 65 70 71 88 89 94 95))
    (:operation :patchify :input-shape (1 3 4 4) :factor 1
     :output-shape (1 16 3)
     :values (0 16 32 1 17 33 2 18 34 3 19 35 4 20 36 5 21 37 6 22 38 7 23 39 8 24 40 9 25 41 10 26 42 11 27 43 12 28 44 13 29 45 14 30 46 15 31 47))
    (:operation :shuffle :input-shape (2 16 3) :factor 2
     :output-shape (2 4 12)
     :values (0 1 2 3 4 5 12 13 14 15 16 17 6 7 8 9 10 11 18 19 20 21 22 23 24 25 26 27 28 29 36 37 38 39 40 41 30 31 32 33 34 35 42 43 44 45 46 47 48 49 50 51 52 53 60 61 62 63 64 65 54 55 56 57 58 59 66 67 68 69 70 71 72 73 74 75 76 77 84 85 86 87 88 89 78 79 80 81 82 83 90 91 92 93 94 95))
    (:operation :shuffle :input-shape (1 16 2) :factor 4
     :output-shape (1 1 32)
     :values (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31))
    (:operation :shuffle :input-shape (2 4 3) :factor 1
     :output-shape (2 4 3)
     :values (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23))))
