(in-package #:cl-docling)
(export '(parse-conversion-arguments))

(defun conversion-integer (text minimum maximum)
  (unless (and (stringp text) (<= 1 (length text) 8) (every #'digit-char-p text))
    (invalid-document "Expected a bounded decimal integer, got ~S." text))
  (let ((value (parse-integer text)))
    (unless (<= minimum value maximum) (invalid-document "Integer outside [~D,~D]." minimum maximum))
    value))

(defun conversion-pages (text)
  (unless (<= 1 (length text) 160) (invalid-document "Invalid page selection length."))
  (let ((pages nil))
    (dolist (part (uiop:split-string text :separator '(#\,)))
      (let* ((range (uiop:split-string part :separator '(#\-)))
             (a (conversion-integer (first range) 1 100000))
             (b (if (second range) (conversion-integer (second range) 1 100000) a)))
        (unless (and (<= (length range) 2) (<= a b) (<= (- b a) 15))
          (invalid-document "Invalid or oversized page range."))
        (loop for n from a to b do
          (when (or (>= (length pages) 16) (and pages (<= n (first pages))))
            (invalid-document "Select at most 16 unique pages in increasing order."))
          (push n pages))))
    (nreverse pages)))

(defun parse-conversion-arguments (arguments)
  "Strict CLI grammar; no model loading, filesystem writes or Lisp reader input."
  (when (equal arguments '("--help")) (return-from parse-conversion-arguments :help))
  (let ((values nil) (seen nil))
    (loop while arguments for name = (pop arguments) do
      (unless (member name '("--input" "--output" "--model" "--pages" "--dpi"
                            "--max-new-tokens" "--task" "--device" "--resume") :test #'equal)
        (invalid-document "Unknown option ~S. Use --help." name))
      (when (member name seen :test #'equal) (invalid-document "Duplicate option ~A." name))
      (push name seen)
      (if (equal name "--resume") (setf (getf values :resume) t)
          (let ((value (pop arguments)))
            (unless (and (stringp value) (<= 1 (length value) 4096)
                         (not (uiop:string-prefix-p "--" value)))
              (invalid-document "Missing/invalid value for ~A." name))
            (setf (getf values (intern (string-upcase (subseq name 2)) :keyword)) value))))
    (unless (and (getf values :input) (getf values :output))
      (invalid-document "--input and --output are required. Use --help."))
    (setf (getf values :pages) (conversion-pages (or (getf values :pages) "1"))
          (getf values :dpi) (conversion-integer (or (getf values :dpi) "144") 1 300)
          (getf values :max-new-tokens) (conversion-integer (or (getf values :max-new-tokens) "512") 1 4096))
    (let ((device (or (getf values :device) "cpu")))
      (unless (member device '("cpu" "gpu") :test #'equal) (invalid-document "Device must be cpu or gpu."))
      (setf (getf values :device) (if (equal device "gpu") :gpu :cpu)))
    values))
