(in-package #:cl-docling)

(defun otsl-cell-kind (tag)
  (cond ((equal tag "ecel") :empty) ((equal tag "fcel") :data)
        ((equal tag "ched") :column-header) ((equal tag "rhed") :row-header)
        ((equal tag "srow") :section-header) (t :span)))

(defun document-table-cells (table)
  "Row-major anchor cells, excluding continuation-marker slots. Do not mutate cells."
  (loop for row in (document-table-rows table) append
    (remove :span row :key #'table-cell-kind)))

(defun resolve-table-spans (rows columns note)
  "Resolve directional markers, then require each owner's coverage to be rectangular."
  (let ((owners (make-array (list (length rows) columns) :initial-element nil))
        (bounds (make-hash-table :test #'eq)))
    (loop for row in rows for r from 0 do
      (loop for cell in row for c from 0 do
        (let* ((left (and (plusp c) (aref owners r (1- c))))
               (above (and (plusp r) (aref owners (1- r) c)))
               (owner
                 (if (not (eq :span (table-cell-kind cell))) cell
                     (cond ((and (equal "lcel" (table-cell-tag cell)) left
                                 (= r (table-cell-row-index left))) left)
                           ((and (equal "ucel" (table-cell-tag cell)) above
                                 (= c (table-cell-column-index above))) above)
                           ((and (equal "xcel" (table-cell-tag cell)) left (eq left above)
                                 (< (table-cell-row-index left) r)
                                 (< (table-cell-column-index left) c)) left)))))
          (setf (aref owners r c) owner)
          (if (null owner)
              (funcall note :table-span (table-cell-start cell) "Orphan or conflicting OTSL continuation marker.")
              (let ((bound (or (gethash owner bounds)
                               (setf (gethash owner bounds) (vector 1 1 0)))))
                (setf (aref bound 0) (max (aref bound 0) (1+ (- r (table-cell-row-index owner))))
                      (aref bound 1) (max (aref bound 1) (1+ (- c (table-cell-column-index owner)))))
                (incf (aref bound 2)))))))
    ;; Directional resolution guarantees all owned slots are at/below/right of
    ;; the anchor. Area equality therefore proves a filled rectangle, not an L.
    (maphash (lambda (cell bound)
               (unless (= (* (aref bound 0) (aref bound 1)) (aref bound 2))
                 (funcall note :table-span (table-cell-start cell) "Merged cell coverage is not rectangular."))) bounds)
    (mapcar (lambda (row)
              (mapcar (lambda (cell)
                        (let ((bound (gethash cell bounds)))
                          (%make-table-cell
                           :tag (table-cell-tag cell) :kind (table-cell-kind cell)
                           :text (table-cell-text cell) :start (table-cell-start cell) :end (table-cell-end cell)
                           :row-index (table-cell-row-index cell) :column-index (table-cell-column-index cell)
                           :row-span (if bound (aref bound 0) 0) :column-span (if bound (aref bound 1) 0)))) row)) rows)))

(defun parse-otsl-table (node raw diagnose)
  "Bounded OTSL grid with validated rectangular spans; invalid tables are never repaired."
  (let ((rows nil) (row nil) (columns 0) (row-size 0) (row-count 0) (count 0)
        (current nil) (pieces nil) (prefix nil) (started nil)
        (renderable (and (doctag-token-closed-p node) (not (doctag-token-malformed-p node)))) (location nil))
    (labels ((note (code start message)
               (setf renderable nil)
               (funcall diagnose code start message))
             (finish-cell (end)
               (when current
                 (when (> (incf count) 4096) (invalid-document "OTSL cell budget (4096) exceeded."))
                 (when (> (incf row-size) 128) (invalid-document "OTSL column budget (128) exceeded."))
                 (let* ((kind (otsl-cell-kind (doctag-token-tag current)))
                        (text (string-trim '(#\Space #\Tab #\Newline #\Return #\Page)
                                           (format nil "~{~A~}" (nreverse pieces))))
                        (start (doctag-token-start current)))
                   (when (if (member kind '(:empty :span)) (plusp (length text)) (zerop (length text)))
                     (note :table-content start "Full cells require text; empty/span markers cannot contain text."))
                   (when (doctag-entity-p text)
                     (note :ambiguous-entity start "Entity-like cell text is not silently decoded."))
                   (when (some (lambda (c) (and (< (char-code c) 32) (not (doctag-space-p c)))) text)
                     (note :control-character start "Control character in table cell."))
                   (push (%make-table-cell :tag (doctag-token-tag current)
                                          :row-index row-count :column-index (1- row-size)
                                          :kind kind :text text :start start :end end) row))
                 (setf current nil pieces nil)))
             (finish-row (start)
               (when (null row) (note :table-shape start "Empty OTSL row."))
               (when (null rows) (setf columns row-size))
               (unless (= row-size columns) (note :table-shape start "OTSL rows must have equal widths."))
               (push (nreverse row) rows)
               (incf row-count)
               (setf row nil row-size 0)))
      (dolist (child (doctag-token-children node))
        (let ((tag (doctag-token-tag child)) (start (doctag-token-start child)))
          (cond
            ((otsl-marker-p tag)
             (setf started t)
             (finish-cell start)
             (if (equal tag "nl") (finish-row start) (setf current child)))
            ((null tag)
             (let ((part (subseq raw start (doctag-token-end child))))
               (cond (current (push part pieces))
                     ((not (doctag-blank-p part)) (note :table-content start "Text outside a table cell.")))))
            ((and (not started) (doctag-prefix-p "loc_" tag)) (push child prefix))
            (t (note :table-content start "Nested markup, cell locations or unknown table tokens are unsupported.")))))
      (finish-cell (if (doctag-token-closed-p node) (- (doctag-token-end node) (length "</otsl>"))
                       (doctag-token-end node)))
      (when row
        (note :table-shape (doctag-token-start node) "Final table row requires an explicit nl marker.")
        (finish-row (doctag-token-end node)))
      (when (null rows) (note :table-shape (doctag-token-start node) "OTSL table has no rows."))
      (setf rows (nreverse rows))
      (when prefix
        (let ((locations-node (make-doctag-token "otsl" (doctag-token-start node) (doctag-token-end node))))
          (setf (doctag-token-children locations-node) (nreverse prefix))
          (setf location (nth-value 1 (doctag-leaf-content locations-node raw #'note)))))
      (when (and rows (plusp columns) (every (lambda (row) (= (length row) columns)) rows))
        (setf rows (resolve-table-spans rows columns #'note)))
      (loop for slots in rows for row-index from 0
            for cells = (remove :span slots :key #'table-cell-kind) do
        (let ((header-count (count :column-header cells :key #'table-cell-kind)))
          (when (or (and (plusp header-count)
                         (or (plusp row-index) (/= header-count (length cells))
                             (some (lambda (cell) (> (table-cell-row-span cell) 1)) cells)))
                    (some (lambda (cell) (member (table-cell-kind cell) '(:row-header :section-header))) cells))
            (note :table-header (doctag-token-start node)
                  "Only a complete first header row without vertical header spans is supported."))))
      (%make-document-element
       :kind :table :tag "otsl" :location location :start (doctag-token-start node) :end (doctag-token-end node)
       :table (%make-document-table :rows rows :column-count columns :renderable-p renderable)))))

(defun markdown-table-cell (cell)
  (let ((text (escape-document-text (table-cell-text cell))))
    (with-output-to-string (out)
      (loop for character across text for index from 0 do
        (cond ((char= character #\Return) (write-string "<br>" out))
              ((char= character #\Newline)
               (unless (and (plusp index) (char= (char text (1- index)) #\Return))
                 (write-string "<br>" out)))
              (t (write-char character out)))))))

(defun html-table-cell-text (text)
  "Escape source text, never source markup. Only the renderer emits HTML tags."
  (with-output-to-string (out)
    (loop for c across text for index from 0 do
      (case c
        (#\& (write-string "&amp;" out)) (#\< (write-string "&lt;" out))
        (#\> (write-string "&gt;" out)) (#\" (write-string "&quot;" out))
        (#\' (write-string "&#39;" out))
        (#\Return (write-string "<br>" out))
        (#\Newline (unless (and (plusp index) (char= (char text (1- index)) #\Return))
                     (write-string "<br>" out)))
        (otherwise (write-char c out))))))

(defun html-merged-table (table)
  (with-output-to-string (out)
    (write-line "<table>" out)
    (dolist (row (document-table-rows table))
      (write-string "<tr>" out)
      (dolist (cell row)
        (unless (eq :span (table-cell-kind cell))
          (let ((tag (if (eq :column-header (table-cell-kind cell)) "th" "td")))
            (format out "<~A" tag)
            (when (> (table-cell-row-span cell) 1) (format out " rowspan=\"~D\"" (table-cell-row-span cell)))
            (when (> (table-cell-column-span cell) 1) (format out " colspan=\"~D\"" (table-cell-column-span cell)))
            (format out ">~A</~A>" (html-table-cell-text (table-cell-text cell)) tag))))
      (write-line "</tr>" out))
    (write-string "</table>" out)))

(defun markdown-table (table)
  (unless (and table (document-table-renderable-p table))
    (return-from markdown-table "[Unsupported table; see raw DocTags.]"))
  (when (some (lambda (cell) (or (> (table-cell-row-span cell) 1) (> (table-cell-column-span cell) 1)))
              (document-table-cells table))
    (return-from markdown-table (html-merged-table table)))
  (let* ((rows (document-table-rows table))
         (has-header (every (lambda (cell) (eq :column-header (table-cell-kind cell))) (first rows))))
    (with-output-to-string (out)
      (flet ((line (values)
               (format out "|~{ ~A |~}" values)))
        (line (if has-header (mapcar #'markdown-table-cell (first rows))
                  (make-list (document-table-column-count table) :initial-element "")))
        (terpri out)
        (line (make-list (document-table-column-count table) :initial-element "---"))
        (dolist (row (if has-header (rest rows) rows))
          (terpri out)
          (line (mapcar #'markdown-table-cell row)))))))
