(in-package #:docling)
(export '(load-vision-model encode-vision vision-model vision-weight-count))

(defstruct (vision-spec (:constructor %vision-spec))
  (layout nil :read-only t) (layers 12 :read-only t)
  (intermediate 3072 :read-only t) (epsilon 1e-6 :read-only t))

(defun read-json-file (path)
  (with-open-file (stream path :external-format :utf-8)
    (yason:parse stream :json-arrays-as-vectors t :json-booleans-as-symbols t)))

(defun parse-vision-spec (config)
  (unless (and (hash-table-p config) (equal (gethash "model_type" config) "idefics3"))
    (invalid-layout "Expected an Idefics3 configuration"))
  (when (gethash "quantization_config" config)
    (invalid-layout "Quantized vision checkpoints are unsupported"))
  (maphash
   (lambda (name value)
     (declare (ignore value))
     (unless (member name '("model_type" "vision_config" "text_config" "scale_factor"
                            "image_token_id" "pad_token_id" "tie_word_embeddings" "torch_dtype"
                            "dtype" "transformers_version" "transformers.js_config" "use_cache"
                            "vocab_size" "_name_or_path" "_commit_hash" "architectures"
                            "return_dict" "output_hidden_states" "output_attentions") :test #'equal)
       (invalid-layout "Unsupported Idefics3 config field ~A" name))) config)
  (let ((vision (gethash "vision_config" config)) (text (gethash "text_config" config)))
    (unless (and (hash-table-p vision) (hash-table-p text))
      (invalid-layout "Missing nested vision/text configuration"))
    (maphash
     (lambda (name value)
       (declare (ignore value))
       (unless (member name '("model_type" "hidden_size" "intermediate_size" "num_hidden_layers"
                              "num_attention_heads" "num_channels" "image_size" "patch_size"
                              "hidden_act" "layer_norm_eps" "attention_dropout" "initializer_range"
                              "torch_dtype" "dtype" "transformers_version" "_name_or_path"
                              "architectures" "tie_word_embeddings" "use_base_siglip" "size"
                              "max_image_size" "return_dict" "output_attentions" "output_hidden_states")
                       :test #'equal)
         (invalid-layout "Unsupported vision config field ~A" name))) vision)
    (unless (and (equal (gethash "model_type" vision "idefics3_vision") "idefics3_vision")
                 (equal (gethash "hidden_act" vision "gelu_pytorch_tanh") "gelu_pytorch_tanh")
                 (eql (gethash "use_base_siglip" vision 'yason:true) 'yason:true)
                 (numberp (gethash "attention_dropout" vision 0))
                 (zerop (gethash "attention_dropout" vision 0)))
      (invalid-layout "Only base SigLIP, tanh GELU and zero dropout are supported"))
    (let* ((layout (make-vision-layout
                    :image-size (gethash "image_size" vision 224)
                    :patch-size (gethash "patch_size" vision 32)
                    :channels (gethash "num_channels" vision 3)
                    :hidden-size (gethash "hidden_size" vision 1152)
                    :num-heads (gethash "num_attention_heads" vision 16)
                    :scale-factor (gethash "scale_factor" config 2)
                    :text-hidden-size (gethash "hidden_size" text)))
           (layers (require-positive-integer (gethash "num_hidden_layers" vision 12) 'layers))
           (intermediate (require-positive-integer (gethash "intermediate_size" vision 3072) 'intermediate))
           (epsilon (gethash "layer_norm_eps" vision 1e-6))
           (side (/ (vision-layout-image-size layout) (vision-layout-patch-size layout))))
      ;; Power-of-two bucket boundaries are represented exactly in FP32. Other grids
      ;; need separate position-boundary qualification against the pinned processor.
      (unless (= 1 (logcount side)) (invalid-layout "Unqualified position grid side ~D" side))
      (unless (and (realp epsilon) (> epsilon 0)) (invalid-layout "Invalid LayerNorm epsilon"))
      (%vision-spec :layout layout :layers layers :intermediate intermediate :epsilon epsilon))))

(defun vision-schema (spec)
  (let* ((layout (vision-spec-layout spec)) (width (vision-layout-hidden-size layout))
         (intermediate (vision-spec-intermediate spec)) (patch (vision-layout-patch-size layout))
         (prefix "model.vision_model.")
         (schema (list (list "model.connector.modality_projection.proj.weight"
                             (vision-layout-text-hidden-size layout) (connector-input-width layout)))))
    (flet ((entry (name &rest shape) (push (cons (concatenate 'string prefix name) shape) schema)))
      (entry "embeddings.patch_embedding.weight" width (vision-layout-channels layout) patch patch)
      (entry "embeddings.patch_embedding.bias" width)
      (entry "embeddings.position_embedding.weight" (patch-count layout) width)
      (entry "post_layernorm.weight" width)
      (entry "post_layernorm.bias" width)
      (dotimes (index (vision-spec-layers spec))
        (dolist (projection '("q_proj" "k_proj" "v_proj" "out_proj"))
          (entry (format nil "encoder.layers.~D.self_attn.~A.weight" index projection) width width)
          (entry (format nil "encoder.layers.~D.self_attn.~A.bias" index projection) width))
        (dolist (norm '("layer_norm1" "layer_norm2"))
          (entry (format nil "encoder.layers.~D.~A.weight" index norm) width)
          (entry (format nil "encoder.layers.~D.~A.bias" index norm) width))
        (entry (format nil "encoder.layers.~D.mlp.fc1.weight" index) intermediate width)
        (entry (format nil "encoder.layers.~D.mlp.fc1.bias" index) intermediate)
        (entry (format nil "encoder.layers.~D.mlp.fc2.weight" index) width intermediate)
        (entry (format nil "encoder.layers.~D.mlp.fc2.bias" index) width)))
    schema))

(defun safetensors-header (file)
  (with-open-file (stream file :element-type '(unsigned-byte 8))
    (let* ((length (loop for shift from 0 below 64 by 8 sum (ash (read-byte stream) shift)))
           (payload (- (file-length stream) 8 length)))
      (unless (and (<= 2 length (* 16 1024 1024)) (>= payload 0))
        (invalid-layout "Invalid or excessive safetensors header size"))
      (let ((bytes (make-array length :element-type '(unsigned-byte 8))))
        (unless (= length (read-sequence bytes stream)) (invalid-layout "Truncated safetensors header"))
        (values (yason:parse (babel:octets-to-string bytes :encoding :utf-8)
                            :json-arrays-as-vectors t :json-booleans-as-symbols t) payload)))))

(defun decoder-weight-p (name)
  (or (and (>= (length name) 17) (string= "model.text_model." name :end2 17))
      (equal name "lm_head.weight")))

(defun validate-vision-header (file schema &key (allow-decoder t))
  (multiple-value-bind (header payload) (safetensors-header file)
    (dolist (entry schema)
      (let ((descriptor (gethash (car entry) header)))
        (unless (and (hash-table-p descriptor)
                     (equal (coerce (gethash "shape" descriptor) 'list) (cdr entry))
                     (member (gethash "dtype" descriptor) '("F32" "F16" "BF16") :test #'equal))
          (invalid-layout "Missing, malformed or incompatible weight ~A" (car entry)))))
    (maphash
     (lambda (name descriptor)
       (unless (equal name "__metadata__")
         (unless (or (assoc name schema :test #'equal) (and allow-decoder (decoder-weight-p name)))
           (invalid-layout "Unexpected weight ~A" name))
         (let ((offsets (gethash "data_offsets" descriptor))
               (shape (gethash "shape" descriptor))
               (bytes (cdr (assoc (gethash "dtype" descriptor)
                                 '(("F32" . 4) ("F16" . 2) ("BF16" . 2)) :test #'equal))))
           (unless (and bytes (vectorp shape) (every (lambda (n) (typep n '(integer 1 2147483647))) shape)
                        (vectorp offsets) (= 2 (length offsets)) (every #'integerp offsets)
                        (<= 0 (aref offsets 0) (aref offsets 1) payload)
                        (= (- (aref offsets 1) (aref offsets 0)) (* bytes (reduce #'* shape))))
             (invalid-layout "Invalid safetensors range for ~A" name))))) header)))
